### ISSUE TITLE
Broken link in Readme

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [square/in-app-payments-flutter-plugin#100]
### Describe the change you would like to see

The First link in the readme for the in app payments is broken.
### How would the suggested change make the documentation more useful?

Update the link

**Comment by StephenJosey** [comment]
Fixed: https://github.com/square/in-app-payments-flutter-plugin/pull/101 thanks for reporting!

**Comment by ThinkDigitalSoftware** [comment]
No problem
