### ISSUE TITLE
Support for new Android Api post-flutter-1.12 in android plugin

### ISSUE THREAD

**Issue by pravinarr** [square/in-app-payments-flutter-plugin#103]
post-flutter-1.12, the android plugin initialization happens through onAttachedToEngine method instead of registerWith. Is there a plan to support this change ?

```
public static void registerWith(Registrar registrar) {
  }
```
to

```
 @Override
  public void onAttachedToEngine(@NonNull FlutterPluginBinding flutterPluginBinding) {
  }
```

**Comment by mohsin-sq** [comment]
This is now supported after the upgrade to support Flutter 1.12+. Please feel free to pull the latest changes and mess around with it. Please reach out if you have any questions or need help configuring it!
