### ISSUE TITLE
Dynamically update `sqipSaveButtonText` for Android customization? 

### ISSUE THREAD

**Issue by tonydiaz** [square/in-app-payments-flutter-plugin#105]
### Describe your question
When customizing the card details: https://github.com/square/in-app-payments-flutter-plugin/blob/master/doc/get-started.md#step-6-customize-card-entry-appearance

Is there a way to make the button text (**sqipSaveButtonText**) dynamic?

In `{YOUR_PROJECT}/android/app/src/main/res/values/themes.xml`: 
 ```
<resources>
    <style name="sqip.Theme.CardEntry" parent="sqip.Theme.BaseCardEntry">
        <item name="sqipSaveButtonText">@string/pay_button</item>
    </style>
</resources>
```
and `{YOUR_PROJECT}/android/app/src/main/res/values/strings.xml`: 
```
<resources>
    <string name="pay_button">Pay %1$s</string>
</resources>
```

When I can pass the amount being charged as the string value (**%1$1s**). For example, _"$5.00"_ turns to _"Pay $5.00_"

Similar to this stackoverflow question: https://stackoverflow.com/questions/3656371/is-it-possible-dynamically-to-add-string-to-string-xml-in-android

**Comment by StephenJosey** [comment]
There is no way to dynamically update this text, unfortunately.

**Comment by tonydiaz** [comment]
Thank you! 

Closing issue.
