### ISSUE TITLE
Flutter Web Support

### ISSUE THREAD

**Issue by nyilkhan** [square/in-app-payments-flutter-plugin#110]
Does this plugin currently support Flutter web integration? I see that web is listed on the plugin page, but did not see any documentation for it. I am trying to integrate a payment gateway into my flutter web app, any help would be appreciated.

**Comment by StephenJosey** [comment]
Unfortunately it is not. There's an existing enhancement for this: https://github.com/square/in-app-payments-flutter-plugin/issues/61
