### ISSUE TITLE
Failed assertion: line 225 pos 12: 'priceStatus != null': priceStatus should not be null.

### ISSUE THREAD

**Issue by recursion0707DCDC** [square/in-app-payments-flutter-plugin#112]
### Describe the change you would like to see
While trying to implement Google Pay, I got the error, `Failed assertion: line 225 pos 12: 'priceStatus != null': priceStatus should not be null.` I'm not sure what priceStatus means and I can't find it online. 

### How would the suggested change make the documentation more useful?
Explain what `priceStatus` is.

### Additional context
The best answer I have gotten was from some example code from another issue, issue #33, which used `google_pay_constants.totalPriceStatusFinal` as the value. While it works, I'm not confident that I'm doing the right thing.. 

The instructions I was following are on this page: https://github.com/square/in-app-payments-flutter-plugin/blob/master/doc/enable-googlepay.md

**Comment by mohsin-sq** [comment]
Hello,

I did some digging and `PriceStatus` seems to be a Google Pay concept and that's how it is introduced into our code. Here is a reference i found around what the different values mean: 
https://developers.google.com/android/reference/com/google/android/gms/wallet/WalletConstants#TOTAL_PRICE_STATUS_FINAL 

I'll see, maybe i can add it as a comment into the appropriate location in the plugin code.

Thanks for bringing it up! I am sure others have similar questions.  Feel free to reach out if there is anything else I can help you with!

Best,
Mohsin
