### ISSUE TITLE
Why I m getting this issue with your example app

### ISSUE THREAD

**Issue by shagilsiddiqui** [square/in-app-payments-flutter-plugin#113]
![Screenshot_20200607-122255](https://user-images.githubusercontent.com/40637140/83962268-beb26580-a8b9-11ea-8098-de6aafa02999.png)
### Describe your question
I have uploaded the image of my error.
Kindly look and tell me.
What is wrong

**Comment by StephenJosey** [comment]
Did you follow this guide correctly? https://github.com/square/in-app-payments-flutter-plugin/blob/master/doc/enable-googlepay.md

Are you trying in sandbox or production?

**Comment by StephenJosey** [comment]
Please reopen if you have further information.
