### ISSUE TITLE
Will this work outside of the US?

### ISSUE THREAD

**Issue by ISimplifyComplexity** [square/in-app-payments-flutter-plugin#125]
I noticed that your prompt asks for a ZIP Code. Here in the UK we use post codes. Will your library support UK payments?

**Comment by StephenJosey** [comment]
Yes, definitely. In fact, you can change the label of the text:

For iOS: https://developer.squareup.com/docs/in-app-payments/localize-ios
For Android, you just change the language of the device.
Please let me know if you have any additional questions or concerns, I'm happy to help!

**Comment by ISimplifyComplexity** [comment]
No that's great thank you
