### ISSUE TITLE
Digital Wallets in Australia

### ISSUE THREAD

**Issue by Kretin1** [square/in-app-payments-flutter-plugin#127]
Are you able to provide an ETA on when digital wallet payments will be supported in Australia?

In the meantime, can you please confirm that card payments through this plugin are supported in Australia?

**Comment by Kretin1** [comment]
@StephenJosey sorry to ping you. I need to support sending orders to the POS, and I'm really hoping to handle Square payments through Apple Pay and Google Pay instead of cards.

**Comment by StephenJosey** [comment]
Hey @Kretin1 no worries at all, apologize that I didn't get to this sooner. Although, unfortunately, I don't have any great news: we do not have any ETAs at the moment on when digital wallets would be made available for Australia.

To answer your other question, though: yes, the regular card payments (not digital wallets) are supported in In-App Payments in Australia.

**Comment by Kretin1** [comment]
Thanks Stephen
