### ISSUE TITLE
Change navigation title in iOS

### ISSUE THREAD

**Issue by bravelocation** [square/in-app-payments-flutter-plugin#128]
I want to be able to change the navigation title of the Square payment widget on iOS.

Basically, the equivalent of the Android string sqipActivityTitle.

Looking through the native iOS docs, you can change this by using UINavigationBar.Appearance(), but I can't find any way of doing this via the Flutter plugin.

Please let me know if I'm missing something!

Thanks
John

**Comment by shivamsaviant** [comment]
Currently, we have this provision only for android. We will add the same for iOS in our backlog.
