### ISSUE TITLE
Saving and retrieving stored cards

### ISSUE THREAD

**Issue by FacePalmDev** [square/in-app-payments-flutter-plugin#129]
Hey, we're looking through your examples and your documentation but we can't find any documentation on how to retrieve stored cards.

Could you point us in the right direction on how to do this?

**Comment by StephenJosey** [comment]
This would be through our general [Customers API](https://developer.squareup.com/docs/customers-api/what-it-does) (outside of In-App Payments SDK). You would need to retrieve the customer, and if the customer had a card on file it would be in the `cards` array. Let me know if you have further questions about this, though.

**Comment by ISimplifyComplexity** [comment]
Thanks for getting back to me so quickly. I wonder then as the component has a save button. Does it have a mechanism to show the cards on file and let the user choose a new card?

**Comment by shivamsaviant** [comment]
Currently, we can achieve this using Customer API as @StephenJosey mentioned in [this](https://github.com/square/in-app-payments-flutter-plugin/issues/129#issuecomment-694462172) comment.
