### ISSUE TITLE
When i implement this plugin on my project, i have facing java.lang.RuntimeException: Duplicate class com.nimbusds.jose.JWEObject found in modules jetified-nimbus-jose-jwt-8.15.jar issue

### ISSUE THREAD

**Issue by seyadubabu** [square/in-app-payments-flutter-plugin#130]
java.lang.RuntimeException: Duplicate class com.nimbusds.jose.JWEObject found in modules jetified-nimbus-jose-jwt-8.15.jar (com.nimbusds:nimbus-jose-jwt:8.15) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class com.nimbusds.jose.JWEObject$State found in modules jetified-nimbus-jose-jwt-8.15.jar (com.nimbusds:nimbus-jose-jwt:8.15) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class com.nimbusds.jose.JWSObject found in modules jetified-nimbus-jose-jwt-8.15.jar (com.nimbusds:nimbus-jose-jwt:8.15) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class com.nimbusds.jose.JWSObject$State found in modules jetified-nimbus-jose-jwt-8.15.jar (com.nimbusds:nimbus-jose-jwt:8.15) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class com.nimbusds.jose.Payload found in modules jetified-nimbus-jose-jwt-8.15.jar (com.nimbusds:nimbus-jose-jwt:8.15) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class com.nimbusds.jose.Payload$Origin found in modules jetified-nimbus-jose-jwt-8.15.jar (com.nimbusds:nimbus-jose-jwt:8.15) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class com.nimbusds.jose.Requirement found in modules jetified-nimbus-jose-jwt-8.15.jar (com.nimbusds:nimbus-jose-jwt:8.15) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class com.nimbusds.jose.crypto.AESEncrypter found in modules jetified-nimbus-jose-jwt-8.15.jar (com.nimbusds:nimbus-jose-jwt:8.15) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class com.nimbusds.jose.crypto.AESEncrypter$AlgFamily found in modules jetified-nimbus-jose-jwt-8.15.jar (com.nimbusds:nimbus-jose-jwt:8.15) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class com.nimbusds.jose.crypto.impl.ECDH found in modules jetified-nimbus-jose-jwt-8.15.jar (com.nimbusds:nimbus-jose-jwt:8.15) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class com.nimbusds.jose.crypto.impl.ECDH$AlgorithmMode found in modules jetified-nimbus-jose-jwt-8.15.jar (com.nimbusds:nimbus-jose-jwt:8.15) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class com.nimbusds.jose.jwk.KeyOperation found in modules jetified-nimbus-jose-jwt-8.15.jar (com.nimbusds:nimbus-jose-jwt:8.15) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class org.spongycastle.crypto.util.DERMacData found in modules jetified-core-1.56.0.0.jar (com.madgag.spongycastle:core:1.56.0.0) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class org.spongycastle.crypto.util.DERMacData$Type found in modules jetified-core-1.56.0.0.jar (com.madgag.spongycastle:core:1.56.0.0) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class org.spongycastle.jcajce.provider.asymmetric.RSA found in modules jetified-prov-1.56.0.0.jar (com.madgag.spongycastle:prov:1.56.0.0) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class org.spongycastle.jcajce.provider.asymmetric.RSA$Mappings found in modules jetified-prov-1.56.0.0.jar (com.madgag.spongycastle:prov:1.56.0.0) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class org.spongycastle.jcajce.provider.asymmetric.rsa.PSSSignatureSpi found in modules jetified-prov-1.56.0.0.jar (com.madgag.spongycastle:prov:1.56.0.0) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class org.spongycastle.jcajce.provider.asymmetric.rsa.PSSSignatureSpi$SHA256withRSA found in modules jetified-prov-1.56.0.0.jar (com.madgag.spongycastle:prov:1.56.0.0) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class org.spongycastle.jcajce.provider.symmetric.AES found in modules jetified-prov-1.56.0.0.jar (com.madgag.spongycastle:prov:1.56.0.0) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class org.spongycastle.jcajce.provider.symmetric.AES$AlgParamsGCM found in modules jetified-prov-1.56.0.0.jar (com.madgag.spongycastle:prov:1.56.0.0) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class org.spongycastle.jcajce.provider.symmetric.AES$ECB found in modules jetified-prov-1.56.0.0.jar (com.madgag.spongycastle:prov:1.56.0.0) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class org.spongycastle.jcajce.provider.symmetric.AES$ECB$1 found in modules jetified-prov-1.56.0.0.jar (com.madgag.spongycastle:prov:1.56.0.0) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class org.spongycastle.jcajce.provider.symmetric.AES$Mappings found in modules jetified-prov-1.56.0.0.jar (com.madgag.spongycastle:prov:1.56.0.0) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  
  Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

**Comment by StephenJosey** [comment]
Does it work in the example project https://github.com/square/in-app-payments-flutter-plugin/tree/master/example ?

**Comment by shivamsaviant** [comment]
Closing this issue. Feel free to reopen or create another issue for any assistance.
