### ISSUE TITLE
Flutter in app payment works in debug mode but not in run mode

### ISSUE THREAD

**Issue by ashleymooney123** [square/in-app-payments-flutter-plugin#131]
I've ensured to check the pubspec.yaml for development dependencies:

dev_dependencies:

I have made sure all dependencies are in the release section:

dependencies:

My in app payment works perfect when testing on actual devices for both android and iOS in debug mode. 
BUT in app payment doesn't work when I download app from App Store (Release mode).

Obviously the plugin is not the issue just looking for assistance myself, I am probably missing something or need a pointer in the right direction. (Thanks for your time)
BUT in app payment doesn't work when I download app from App Store (Release mode).

Obviously the plugin is not the issue just looking for assistance myself, I am probably missing something or need a pointer in the right direction. (Thanks for your time)

**Comment by StephenJosey** [comment]
Are you getting any sort of errors or what happens when you try to use it after downloading from the app store?

**Comment by ashleymooney123** [comment]
It works on my IOS when I download from AppStore.
When I download from play store for Android, I type in all my credit card credentials/ test card “4111 1111 1111 1111” ect. But the app just crashed / goes to my home / start screen of my app. 

It’s strange because when I test it on the emulator it works & the payment goes through with android

**Comment by ashleymooney123** [comment]
Any idea what is causing this . I am still at a standstill .

Regards,

**Comment by StephenJosey** [comment]
Apologies for the delay; could you share your application id? I can see if I can find anything obvious in our logs to might show what's going on.

**Comment by ashleymooney123** [comment]
My applicationId: "sqip.flutter.geodeArt"

**sqip.flutter.geodeArt**

I am thinking there is something silly that I am missing, considering it works on emulator , but fails on both android devices that I have tried, after downloading from App Store. (Both using the fake 4111-1111-1111-1111 card number or using a real card #)

Thanks so much for your response. Let me know if you think of anything.

**Comment by ashleymooney123** [comment]
I do get the following message when building my appbundle:

**_Note: /Users/ashleymooney/Desktop/in-app-payments-flutter-plugin-master/android/src/main/java/sqip/flutter/internal/CardEntryModule.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details._**

Unsure if this could be related to my issue with payment not working on android devices

**Comment by StephenJosey** [comment]
Thanks for the info, sorry I meant your Square application id. Not sure if I can find the logs by the actual application id.

**Comment by ashleymooney123** [comment]
sq0idp-XVbcSkfmHHhgOwhwYc5LAw

Let me know if you need any other information

**Comment by ashleymooney123** [comment]
I think this has to do with the version of flutter I am running. 
What is the latest version of flutter I should be running Channel stable, **v1.9.1+hotfix.6** ?

Or does the square in app payment SDK now work fully in version v1.12?

I need to know what flutter version to be running in order to make the in app payment work in release mode for android

**Comment by ashleymooney123** [comment]
My app finally works android and ios on the app store ! 
Using flutter channel stable v1.12.13+hotflix.9

I was using flutter version 1.22.0 when the app was crashing on android in release mode 

Thanks
