### ISSUE TITLE
How to know if the user clicked the save button or if they just want to pay?

### ISSUE THREAD

**Issue by FacePalmDev** [square/in-app-payments-flutter-plugin#132]
I see that when the save button is pressed I get a nonce back using the callback. 

What if the user just wants to pay using the new card? How do I figure out which action they were trying to perform?

**Comment by StephenJosey** [comment]
A nonce can be used to charge a customer immediately _or_ save the card on file. It's up to your application to distinguish the two use-cases and flow, though. You might have a button that says "Pay now" with a checkbox that says "Save card information for next time?" and if they check it, then you would save the card on file and then charge it. However, that's just a suggestion, ultimately it's up to you and your app on how to tell what the customer is trying to do. You can definitely rename the button to anything (besides "Save") as well.

**Comment by shivamsaviant** [comment]
Closing this issue. Feel free to reopen or create another issue for any assistance.
