### ISSUE TITLE
initializeApplePay Not Working

### ISSUE THREAD

**Issue by dirjud** [square/in-app-payments-flutter-plugin#134]
### Describe your question

When I call:

      await InAppPayments.initializeApplePay('merchant.run.oyo.app');
      canUseApplePay = await InAppPayments.canUseApplePay;

canUseApplePay is false. How do I figure out why it is false? I have the merchant id and certificate created. I am not sure if it could be related to certificates or not. What exactly is canUseApplePay checking?

**Comment by StephenJosey** [comment]
Not sure of all checks off the top of my head, but at the very least, Apple Wallet needs to be enabled and there needs to be at least one card added there (not to mention this will only work on iOS devices of course). Are these things all true?

**Comment by dirjud** [comment]
Turns out it was a issue with the card that I thought was added. Once I got it added correctly, the canUseApplePay returned true. Thanks for your feedback.

**Comment by StephenJosey** [comment]
Ah, great, thanks for confirming. I'll close this out, but let us know if you run into anything else of course!
