### ISSUE TITLE
Clarification regarding issue #87

### ISSUE THREAD

**Issue by AlexanderArendar** [square/in-app-payments-flutter-plugin#135]
In https://github.com/square/in-app-payments-flutter-plugin/issues/87 it is stated by the resolver that with v1.5.0 of the plugin I can use v7.0.0 of the built_value package.
But when I try to do so it fails.
I've set square_in_app_payments: ^1.5.0 and built_value: ^7.0.0, built_value_generator: ^7.0.0.

When trying to flutter pub get it fails with this message:

alex@old-horse:/mnt/sdb/projects/aicamping/ui_flutter_demo$ flutter pub get
Because square_in_app_payments 1.5.0 depends on built_value ^6.1.5 and no versions of square_in_app_payments match >1.5.0 <2.0.0, square_in_app_payments ^1.5.0 requires built_value ^6.1.5.
So, because eventhut depends on both built_value ^7.0.0 and square_in_app_payments ^1.5.0, version solving failed.

I've commented in the #87 but not sure if anyone will take a look at the closed issue comment.
Could you advice?

As I see [here](https://pub.dev/packages/square_in_app_payments/versions) v1.5.0 was released on July 10th and the commit was made on July 15th as can be seen [here](https://github.com/square/in-app-payments-flutter-plugin/pull/123/commits/812d2085af6b9572395cc77a7c4a35cff96824c6).

**Comment by StephenJosey** [comment]
You can see in the [pubspec](https://github.com/square/in-app-payments-flutter-plugin/blob/master/pubspec.yaml), that it indeed is using `built_value: ^7.0.0` so I'm not sure why you would be getting that error. It is also definitely version 1.5.0, so I'm not really understanding what is happening in the above.

**Comment by AlexanderArendar** [comment]
@StephenJosey  you should be mixing up things.
If you go here: https://pub.dev/packages/square_in_app_payments/versions and download 1.5.0 zip you will see that the pubspec.yaml has `built_value: ^6.1.5`.
You commit was merged to master AFTER 1.5.0 version was released.

**Comment by StephenJosey** [comment]
Ah, you are correct! I will alert the team to push this out. Stand by, will update once I have more info from them. Thanks!

**Comment by StephenJosey** [comment]
This should be resolved here in 1.5.1: https://pub.dev/packages/square_in_app_payments/versions

**Comment by AlexanderArendar** [comment]
Thank you
