### ISSUE TITLE
Error: 

### ISSUE THREAD

**Issue by ashleymooney123** [square/in-app-payments-flutter-plugin#137]
I got the Plugin working fine on both Android and Apple in my final flutter app in the App Store.
Days / Weeks later, I now receive this error:

I/flutter (19331): {errors: [{code: BAD_REQUEST, detail: This account has not been enabled to take payments, category: INVALID_REQUEST_ERROR}]}

Does this suggest the issue lays with Square themselves?
I have not received any emails regarding my account having an issue...

Regards,

**Comment by StephenJosey** [comment]
Hi @ashleymooney123 that is strange! Could you provide the merchant/location id that you're trying to take payments for? I can look up in our system to see if there's something going on with your account.

**Comment by ashleymooney123** [comment]
Location ID: X7ZKSMN4J1W4T

Do you require the Application ID as well?

**Comment by ashleymooney123** [comment]
Hello Stephen,

Turns out my account was deactivated

Now it is reactivated I recieved an email from square 👍 

"
Hello Ashley,
--
Thank you for your patience while we reviewed your account.
We are happy to inform you that we have re-activated your account and funds due to you will be sent for deposit to your linked bank account tonight. Depending on your bank, you should see the funds in your account within 1-2 business days.
Moving forward, you will be able to continue processing your payments with Square. In order to ensure a secure purchasing environment, we may periodically contact customers for additional information. Review our merchant protection guidelines and tips for safely accepting payment cards.
Sincerely,
Square Account Services
"

I am unsure why this happened. I am hoping all is well now, and this may have happened because I did small payments (cent values) when testing my app because of my issues with the flutter version when launching on app store. Now i am hoping all is well I may need to investigate further. I wish the email would give some information as to why I was deactivated, thanks for your assistance and fast reply.

Regards,
