### ISSUE TITLE
Exception thrown when calling onCardEntryComplete when using buyer verification (Android only)

### ISSUE THREAD

**Issue by bravelocation** [square/in-app-payments-flutter-plugin#140]
When calling InAppPayments.completeCardEntry in our onBuyerVerificationSuccess handler from InAppPayments.startCardEntryFlowWithBuyerVerification(...), we get the following exception:

```
Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'void java.util.concurrent.CountDownLatch.countDown()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.concurrent.CountDownLatch.countDown()' on a null object reference
E/flutter (27369): 	at sqip.flutter.internal.CardEntryModule.completeCardEntry(CardEntryModule.java:129)
E/flutter (27369): 	at sqip.flutter.SquareInAppPaymentsFlutterPlugin.onMethodCall(SquareInAppPaymentsFlutterPlugin.java:74)
E/flutter (27369): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (27369): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (27369): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter (27369): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (27369): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter (27369): 	at android.os.Looper.loop(Looper.java:174)
E/flutter (27369): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/flutter (27369): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (27369): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/flutter (27369): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter (27369): )
```

N.B. This is Android only - the code works perfectly on iOS.

I'm not a Java expert, but looking in CardEntryModule.java, it looks to me that the countdownLatch is not initialised if we have set contact details, as we do when using BuyerVerification (i.e. the code returns immediately at line 88 without initialising the countdownLatch)

Therefore in the completeCardEntry method, it should check countdownLatch is not null before trying to call countDown() on it (line 129, and I'm assuming at line 135 too)?

Alternately, initialise the countdownLatch before line 88?

This is using the 1.5.1 plugin, which I believe is the latest version, developing on MacOS, on all versions of Android I've tested on.

flutter doctor -v gives:

```
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-arm, locale en-GB)
    • Flutter version 1.22.5 at /Users/john/Documents/development/flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/john/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (2 available)
    • Pixel (mobile)             • FA69J0311101                         • android-arm64 • Android 10 (API 29)
    • iPhone 11 Pro Max (mobile) • BA25E1D0-EEE6-43D6-9148-C627D2236842 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
```

Please let me know if you need any more information

**Comment by bravelocation** [comment]
Alternate theory is that I misunderstood/misread the documentation, and we don't need to/shouldn't call InAppPayments.completeCardEntry() when we are using buyer verification?

Removing the call (obviously) removes the exception, and doesn't appear to cause any problems in the payment flow.

**Comment by StephenJosey** [comment]
Thanks for reporting this. I've shared it with our SDK team and will follow up once I have more information!

**Comment by geekydiamond** [comment]
I have the same issue. Just switched to startCardEntryFlowWithBuyerVerification on a system that has been taking payments happily for the last two years, and instantly hit this issue.

The payment was successfully taken, so this looks like some kind of clean-up activity.

Looks like @bravelocation gave a really great description of the issue. This is blocking our SCA rollout, which is getting near, so could you look at this as a priority please?

**Comment by rmorrin** [comment]
@StephenJosey Are there any updates on this? We're also blocked by this for our SCA compliance

**Comment by hukid** [comment]
@rmorrin, @geekydiamond, @bravelocation Sorry about the confusing doc, the `completeCardEntry` is not required in the SCA workflow, so you just don't need to call that method and everything will work fine.

We've added more description in the doc with the PR #157.
