### ISSUE TITLE
[iOS] Touch event on SDK native screen is also passed to Flutter screen behind it.

### ISSUE THREAD

**Issue by TheVinhLuong** [square/in-app-payments-flutter-plugin#142]
### Describe the issue
 This issue is a well-known Flutter issue here: https://github.com/flutter/flutter/issues/14720
 
### To Reproduce
  1. Adding a print line to `Buy` button in Flutter screen
  2. Select `Pay with card`
  3. At a native screen, touch at a coordinate which the `Buy` button (in Flutter screen in the back) is located at. It will print out the line we added at step 1

### Expected behavior
Not printing anything

**Environment (please complete the following information):**
  - platform: iOS
  - OS and version: 14.3
  - dev environment: MacOS
  - In-App Payments Plugin version: commit hash `10c33027432a6513d1174a40e955e63fe698874f`

  In addition: Run `flutter doctor -v` in your terminal and copy the results here.
[✓] Flutter (Channel stable, 1.22.2, on macOS 11.1 20C69, locale en-VN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
[✓] VS Code (version 1.52.1)
[✓] Connected device (2 available)

**Comment by hukid** [comment]
@TheVinhLuong Since this is a flutter issue, we may wait for flutter to fix it. We've updated the package to support flutter 2.

**Comment by shivamsaviant** [comment]
Closing this issue.
