### ISSUE TITLE
Support for new major version of built_value (^8.0.2)

### ISSUE THREAD

**Issue by 7sergiy** [square/in-app-payments-flutter-plugin#143]
Running "flutter pub get":

`Because square_in_app_payments >=1.5.1 depends on built_value ^7.0.0 and xxx depends on built_value ^8.0.2, square_in_app_payments >=1.5.1 is forbidden.`

@StephenJosey , could you please manage and address this?

**Comment by StephenJosey** [comment]
Thanks for sharing, I will provide this to the team and follow up once I have more info.

**Comment by 7sergiy** [comment]
@StephenJosey , any progress? 

It is **critical** issue. 

After Flutter 2.x release, other libs, like "google_maps_flutter" and "google_maps_flutter_web" and others, requires built_value 8.x - as otherwise you'll get chain dependencies conflicts in your app if trying to build it with built_value 7.x.
