### ISSUE TITLE
Flutter 2.x null safety support is missing

### ISSUE THREAD

**Issue by xiyulangzi** [square/in-app-payments-flutter-plugin#144]
upgrade to flutter 2.x nullsafety enabled

in-app-payments-flutter-plugin need support null safety for all app upgrade.

>dart pub upgrade --null-safety --dry-run
null-safety compatible versions do not exist for:
 - square_in_app_payments

**Comment by xiyulangzi** [comment]
Hi,  Square team,

The package's support of null-safety issue is Critical and stop its user to migrate the app.
would it be possible to plan the work asap and give some timeline?

Thanks.

**Comment by hukid** [comment]
@xiyulangzi we are actively working on this fix now. An pr should be ready by end of this week. We'll send you an update once it's ready.
