### ISSUE TITLE
Crash on clicking SAVE button

### ISSUE THREAD

**Issue by ankitpanwar8979** [square/in-app-payments-flutter-plugin#150]
Initially it was working perfectly but after i tried to add firebase notification to my project this is getting crash in android side only.

I added "apply plugin: 'com.google.gms.google-services'" in app/build.gradle and classpath 'com.google.gms:google-services:4.3.3' in android/build.gradle file and run in android.

In Card Entry Page after i enter the card details when i click SAVE button, the indicator animates and the after 1 2 seconds it crashes.

this is the error

```
E/AndroidRuntime(24359): FATAL EXCEPTION: CardResultHandler
E/AndroidRuntime(24359): Process: com.possibility.algo, PID: 24359
E/AndroidRuntime(24359): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
E/AndroidRuntime(24359): 	at sqip.flutter.internal.CardEntryModule$1.handleEnteredCardInBackground(CardEntryModule.java:96)
E/AndroidRuntime(24359): 	at sqip.internal.CardEntryActivityController$onCardNonceSuccess$1.run(CardEntryActivityController.kt:151)
E/AndroidRuntime(24359): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(24359): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(24359): 	at java.lang.Thread.run(Thread.java:919)
```

Please help me with this issue.

**Comment by jguze** [comment]
Hi @ankitpanwar8979. Can you help us with a few details:
1. What version of the square_in_app_payments plugin are you using?
2. What version of the Square In App Payments SDK are you using?
3. Does this only happen when you add the Google Services plugin?

**Comment by ankitpanwar8979** [comment]
hey @jguze, thanks for reply
here is the details you asked

1. I am using square_in_app_payments 1.6.0.
2. In android its 1.4.0, which is default you are using in this package
3. Yes, this happens only after adding Google Services plugin, otherwise its working fine.

**Comment by ankitpanwar8979** [comment]
Hey there, have you found any solution for this?

**Comment by hukid** [comment]
@ankitpanwar8979 We are not sure if there is a conflict issue with the native SDK. Can you try a different version (like `1.5.0`) and check if that fixes the issue?

**Comment by ankitpanwar8979** [comment]
I tried downgrade the flutter package to 1.5.0 and also tried upgrading the android library by overriding it to 1.5.0 but it didn't worked.

**Comment by hukid** [comment]
@ankitpanwar8979 I tried to reproduce the issue but failed, here is the change that I tried: https://github.com/square/in-app-payments-flutter-plugin/pull/153

Can you please let me know what else you have done?

**Comment by ankitpanwar8979** [comment]
Hey @hukid, i checked my code for the exact issue and tried with your example app and i found same error with below changes in your app

1. In `pubspec.yml`, i added below dependencies

```
  firebase_core: ^0.7.0
  firebase_messaging: ^8.0.0-dev.15

```

2. In `main.dart` file

```
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  // If you're going to use other Firebase services in the background, such as Firestore,
  // make sure you call `initializeApp` before using other Firebase services.
  await Firebase.initializeApp();

  print("Handling a background message: ${message?.data??""}");
}

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
  runApp(MaterialApp(
    title: 'Super Cookie',
    home: HomeScreen(),
  ));
}
```

3. added `google-services.json` file
4. added `classpath 'com.google.gms:google-services:4.3.5'` in android/build.gradle
5. added `apply plugin: 'com.google.gms.google-services'` in app/build.gradle

thats all and then run app you will get crash.
Thank you.

**Comment by hukid** [comment]
@ankitpanwar8979 this #154 should fix the issue.

**Comment by ankitpanwar8979** [comment]
This one fixed for me with your new commit.

Thanks a lot.

**Comment by hukid** [comment]
@ankitpanwar8979 great! Thanks for  your patience and working with us to debug the issue! We'll publish the new version soon.
