### ISSUE TITLE
onCardEntryCancel Not triggering if modal is swiped away IOS (CANCEL BUTTON NOT PRESSED)

### ISSUE THREAD

**Issue by saho-ventures** [square/in-app-payments-flutter-plugin#159]
### Describe the issue
on canceled callback is not called by SDK when card entry is dismissed via swipe on IOS. Works fine if cancel button is used.

### To Reproduce
  Steps to reproduce the issue.

  For example - 
  1. Initialize the SDK
  2. Start card entry
  3. Swipe down to dismiss modal for card entry
  4. No callback for cancel

  Here the piece of code that reproduce the issue.

   Future<void> _onStartCardEntryFlow() async {

    .....

    await InAppPayments.startCardEntryFlow(onCardNonceRequestSuccess: _onCardEntryCardNonceRequestSuccess,
        onCardEntryCancel: _onCancelCardEntryFlow);

  }
  ......

void _onCancelCardEntryFlow() {

    // Handle the cancel callback
   print("Callback called");
  }

### Expected behavior
I excepted the sdk to call the on cancel callback.

**Environment (please complete the following information):**
  - platform: IOS
  - OS and version: [e.g. iOS8.1] 14.5
  - dev environment: MacOS
  - In-App Payments Plugin version: 1.7.1

Thanks
-Steve

**Comment by mdeandrea-mrmilu** [comment]
This is a requirement to improve UX, which would allow adding a loader when switching between saved card mode and web view to add token, for example

**Comment by CharmisG** [comment]
Fixed it in latest update.
