### ISSUE TITLE
error card error

### ISSUE THREAD

**Issue by tegab** [square/in-app-payments-flutter-plugin#16]
I am getting card_entry_unauthorized error.  Any chance someone can please help with a solution. 

Thank You

**Comment by StephenJosey** [comment]
Did you replace your application_id with your production Square application id? If so, does this error occur during the card entry form?

**Comment by StephenJosey** [comment]
Hi @tegab, just checking in to see if this was resolved?

**Comment by tegab** [comment]
> Hi @tegab, just checking in to see if this was resolved?

it works now.  thank you.  

i have a major issue charging dollar amount with cents.  i have to *100 to make it work. how do i go about charging user, example $5.89.



$request_body = array (
  "card_nonce" => $nonce,
  
  "amount_money" => array (
    "amount" => ((int)$json_obj["amount"])*100,
    "currency" => "CAD",
    'description' => $json_obj["description"],
  ),
   

  "idempotency_key" => uniqid()
);

**Comment by StephenJosey** [comment]
That is what you would do. Since `Charge` uses the lowest denomination, you must always pass the value in cents. So $5.89 would be 5.89 * 100 = 589.

**Comment by StephenJosey** [comment]
@tegab was this resolved?

**Comment by tegab** [comment]
> @tegab was this resolved?

yes.  thnx.


not sure if i should start another post. 

Can you please  explain how I am able to debug apple pay and google pay.  really appreciate all the support.

**Comment by StephenJosey** [comment]
I see another issue was created, so we'll close this one for now. Thanks!
