### ISSUE TITLE
Firebase messaging  help

### ISSUE THREAD

**Issue by henry2327** [square/in-app-payments-flutter-plugin#160]
note: recompile with -xlint:deprecation for details. c:\src1\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-9.1.4\android\src\main\java\io\flutter\plugins\firebase\messaging\flutterfirebasemessagingplugin.java:20: error: cannot find symbol import com.google.firebase.iid.firebaseinstanceid;

**Comment by shivamsaviant** [comment]
Hi @henry2327, Can you provide `Flutter doctor -v` and minimal reproducible sample in a repository?
Thank you
