### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tegab** [square/in-app-payments-flutter-plugin#17]
i am getting error

[!] CocoaPods could not find compatible versions for pod "square_in_app_payments":

please help

**Comment by StephenJosey** [comment]
Does this just happen when you are trying to run the program? You shouldn't need to run anything regarding CocoaPods with Flutter. Can you please provide the full error log?

**Comment by StephenJosey** [comment]
Also, can you confirm that in your Podfile you see `platform :ios, '11.0'`? If it's any other number (like 10.0), please change it to 11.0.

**Comment by tegab** [comment]
I will try that today.  Hope this works.

**Comment by StephenJosey** [comment]
Hey @tegab just checking back in - were you able to get this working? Definitely don't hesitate to ask further questions!

**Comment by tegab** [comment]
It worked. Thnx.

**Comment by james-knott** [comment]
Getting same error. Podfile says 11.0

**Comment by garrettmortara** [comment]
Me as well! Please help. I set my Podfile to 12.0

**Comment by garrettmortara** [comment]
@james-knott @StephenJosey I'm having the same problem. Did you manage to get it working? I set my Podfile to 12.0.

**Comment by garrettmortara** [comment]
Whoops, figured it out. You can't just edit the text in the Podfile, you also have to change the settings in Xcode. Click on Runner in the Project Navigator, go to the info tab and change the deployment target to 11.1.

**Comment by chrisogonas** [comment]
> Whoops, figured it out. You can't just edit the text in the Podfile, you also have to change the settings in Xcode. Click on Runner in the Project Navigator, go to the info tab and change the deployment target to 11.1.

Oh... huh!!! How much you saved me a tonne of headache after days and days of combing through the error without any clear explanation of the cause! Thanks lots, @garrettmortara

**Comment by NareshKosgi** [comment]
I'm running into this issue as well, tried 10, 11, 12 14 on Podfile no dice on any of them, any idea how to fix this issue? using version 1.7.2
