### ISSUE TITLE
Didn't find class "sqip.internal.w2.lJsonAdapter" 

### ISSUE THREAD

**Issue by MazenCoder** [square/in-app-payments-flutter-plugin#175]
When I click on pay

`await InAppPayments.startCardEntryFlow(
          onCardNonceRequestSuccess: _onCardEntryCardNonceRequestSuccess,
          onCardEntryCancel: _onCancelCardEntryFlow, collectPostalCode: false,
 );`

**the app keeps stopping when the app running in the release.**

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.academy.app/sqip.internal.CardEntryActivity}: java.lang.RuntimeException: Failed to find the generated JsonAdapter class for class sqip.internal.nonce.j

E/AndroidRuntime(10153): FATAL EXCEPTION: main
E/AndroidRuntime(10153): Process: com.academy.app, PID: 10153
E/AndroidRuntime(10153): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.academy.app/sqip.internal.CardEntryActivity}: java.lang.RuntimeException: Failed to find the generated JsonAdapter class for class sqip.internal.w2.l
E/AndroidRuntime(10153):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2720)
E/AndroidRuntime(10153):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2781)
E/AndroidRuntime(10153):        at android.app.ActivityThread.-wrap12(ActivityThread.java)
E/AndroidRuntime(10153):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1508)
E/AndroidRuntime(10153):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(10153):        at android.os.Looper.loop(Looper.java:241)
E/AndroidRuntime(10153):        at android.app.ActivityThread.main(ActivityThread.java:6274)
E/AndroidRuntime(10153):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10153):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/AndroidRuntime(10153):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
E/AndroidRuntime(10153): Caused by: java.lang.RuntimeException: **Failed to find the generated JsonAdapter class for class sqip.internal.w2.l**

**Comment by brigadierpratap** [comment]
Any updates on this? I have the same issue!

**Comment by brigadierpratap** [comment]
It turns out, this is the issue with R8.
Simply go to the app/build.gradle add the following config in builtdTypes->release.

`
           minifyEnabled true
           proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
`

Create a "proguard-rules.pro" file in app folder and write
`
-keep class sqip.** { *; }
`
