### ISSUE TITLE
Play Store error 

### ISSUE THREAD

**Issue by TisseraK** [square/in-app-payments-flutter-plugin#177]
### Describe the issue
Hy,
After build an appbundle or an APK, when i upload on Google Play Store, i have this error : 

           `You uploaded an APK or Android App Bundle that has an activity, activity alias, service, or broadcast receiver with an intent filter, but the "android:exported" property is not set. This file cannot be installed on Android 12 or later. See developer.android.com/about/versions/12/behavior-changes-12#exported`

I already add on main activity : `<activity android:name="sqip.internal.SecureRemoteCommerceActivity"
    android:exported="false"
    tools:node="merge" />`
And already done all that was necessary.
I dont really understand what i miss.
Thanks for help and have a good day

**Comment by jayczech23** [comment]
Hi @TisseraK 

I would be curious to see if there are any other components in your manifest file that include <intent-filter>?

**Comment by CharmisG** [comment]
Just need to add export line in manifest.
It's resolved in latest update.
