### ISSUE TITLE
Payment Error(on iOS) and can't able to debug/build on android

### ISSUE THREAD

**Issue by RomeoDar** [square/in-app-payments-flutter-plugin#184]
### Describe the issue

Issue No. 1: => I'm trying to complete a payment via card payment, it was working fine few days ago but now whenever I try to proceed for payment by entering test card credentials (4111 1111 1111 1111 12/23 123 123) its giving me error i.e. "Payment error, please contact support if error persist". in debug it doesn't gives/show any error. Screenshot attached
 
 
![EED1BD53-935E-4D23-A5B8-AA25512F6CB1](https://user-images.githubusercontent.com/52714884/162606025-e01155d6-855f-479a-b576-9ca0c39b9bc9.png)

 Issue No. 2: => Also apart from this issue on iOS, whenever I try to debug/run the app on android device it gives following error:
 
 Launching lib/main.dart on V2061 in debug mode...
Running Gradle task 'assembleDebug'...
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve net.minidev:json-smart:[1.3.1,2.3].
     Required by:
         project :app > project :square_in_app_payments > com.squareup.sdk.in-app-payments:buyer-verification:1.5.5 > com.squareup.sdk.in-app-payments:buyer-verification-internals:1.5.5 > com.nds.threeds:widget:1.3.8 > com.nds.threeds:core:1.3.8 > com.nds.threeds:threedssdk-release:1.10.6
      > Failed to list versions for net.minidev:json-smart.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/net/minidev/json-smart/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/net/minidev/json-smart/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/net/minidev/json-smart/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 2m 17s
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...

<img width="1440" alt="Screenshot 2022-04-09 at 11 50 44 PM" src="https://user-images.githubusercontent.com/52714884/162606192-7eb3708b-86ef-4d09-8580-7342d9022aed.png">

**Environment (please complete the following information):**

**Comment by CharmisG** [comment]
Resolved in latest update.
