### ISSUE TITLE
Gradle issue

### ISSUE THREAD

**Issue by jay2jp** [square/in-app-payments-flutter-plugin#192]
Im having this gradle issue when I migrate from minsdk version 21 to 24 after installing this package 

':app:checkDebugDuplicateClasses'
 
flutter doctor 
':app:checkDebugDuplicateClasses'

`
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.3.1 21E258 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.67.2)
[✓] Connected device (2 available)
`
full logs 
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/17814331/175430397-5961ac2f-677b-45b9-949a-dfc803a69115.png">

**Comment by taqi92** [comment]
i'm also facing the issue, any solution or update on this?

**Comment by CharmisG** [comment]
@jay2jp 
We have resolved this issue please check in latest code.
