### ISSUE TITLE
I have error when build android app

### ISSUE THREAD

**Issue by attractfront** [square/in-app-payments-flutter-plugin#203]
This error wasn't few days ago but became today
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve net.minidev:json-smart:[1.3.1,2.3].
     Required by:
         project :app > project :square_in_app_payments > com.squareup.sdk.in-app-payments:buyer-verification:1.5.6 > com.squareup.sdk.in-app-payments:buyer-verification-internals:1.5.6 > com.nds.threeds:widget:1.3.9 > com.nds.threeds:core:1.3.9 > com.nds.threeds:threedssdk-release:1.10.7
      > Failed to list versions for net.minidev:json-smart.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml.
            > Could not GET 'https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml'.
               > Read timed out

I think it is connected with jcenter() in build.gradle

Could you please check it?

**Comment by AbdrahumanFikry** [comment]
same !

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve net.minidev:json-smart:[1.3.1,2.3].
     Required by:
         project :app > project :square_in_app_payments > com.squareup.sdk.in-app-payments:buyer-verification:1.5.6 > com.squareup.sdk.in-app-payments:buyer-verification-internals:1.5.6 > com.nds.threeds:widget:1.3.9 > com.nds.threeds:core:1.3.9 > com.nds.threeds:threedssdk-release:1.10.7
      > Failed to list versions for net.minidev:json-smart.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml'.
               > Read timed out`

**Comment by CharmisG** [comment]
Hello @attractfront  @AbdrahumanFikry ,

@AbdrahumanFikry 

please replace your gradle.properties with below code,

org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
android.proguard.enableRulesExtraction=true

and change compileSDK and targetSDK version to 32 in app build.gradle.

and let me know if you are still facing same.

**Comment by CharmisG** [comment]
Closing this issue but if you still find this problem please reopen this issue. Thank you.
