### ISSUE TITLE
Build Error 

### ISSUE THREAD

**Issue by AbdrahumanFikry** [square/in-app-payments-flutter-plugin#204]
# Build Error
### Here is the log:
  ```
  FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve net.minidev:json-smart:[1.3.1,2.3].
     Required by:
         project :app > project :square_in_app_payments > com.squareup.sdk.in-app-payments:buyer-verification:1.5.6 > com.squareup.sdk.in-app-payments:buyer-verification-internals:1.5.6 > com.nds.threeds:widget:1.3.9 > com.nds.threeds:core:1.3.9 > com.nds.threeds:threedssdk-release:1.10.7
      > Failed to list versions for net.minidev:json-smart.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml'.
               > Read timed out
  ```

**Comment by CharmisG** [comment]
@AbdrahumanFikry 
What is your distributionUrl version in gradle-wrapper.properties ??

**Comment by AbdrahumanFikry** [comment]
@CharmisG 
`
distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-all.zip
`

**Comment by CharmisG** [comment]
@AbdrahumanFikry 

please replace your gradle.properties with below code,

org.gradle.jvmargs=-Xmx1536M --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED
android.jetifier.ignorelist=moshi-1.13.0
android.useAndroidX=true
android.enableJetifier=true
android.proguard.enableRulesExtraction=false

and let me know if you are still facing same.

**Comment by CharmisG** [comment]
Closing this issue but if you still find this problem please reopen this issue. Thank you.
