### ISSUE TITLE
Using both square_in_app_payments and square_reader in the  same project

### ISSUE THREAD

**Issue by dirjud** [square/in-app-payments-flutter-plugin#210]
We have an internal flutter library that includes the square_in_app_payments. I have an app that includes the square_reader and that library. When I try to build, I get a duplicate class error:

>  Execution failed for task ':app:checkReleaseDuplicateClasses'.
> > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
>    > Duplicate class com.squareup.Pan found in modules jetified-card-42 (com.squareup.android:card:42) and jetified-reader-sdk-internals-1.7.4 (com.squareup.sdk.reader:reader-sdk-internals:1.7.4)

I am wondering if there is a way to include both in the same project?

**Comment by plinio-square** [comment]
If by Square Reader you mean Reader SDK, we don't support running both SDKs in the same application.
