### ISSUE TITLE
Ios signing issue

### ISSUE THREAD

**Issue by geekydiamond** [square/in-app-payments-flutter-plugin#22]
Hi all,

The plugin is working beautifully on Android and ios test devices and looks great!

However, when I try to publish the ios app to the app store in xcode I'm getting a signing issue:
```ERROR ITMS-90035: "Invalid Signature. Code object is not signed at all. The file at path [Runner.app/Frameworks/SquareInAppPaymentsSDK.framework/setup] is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html"```

I have many other plugins in the project (e.g. firebase) that had no problems, and I've released to the app store many times before. I've removed and added the square plugin to ensure it is this plugin that is causing the problem and it is.

I've tried cleaning projects, recreating certificates, manually setting provisioning profiles, etc but nothing seems to move the needle. My next step is to completely recreate the project from scratch :(

Any help gratefully received!
Tom

**Comment by geekydiamond** [comment]
Completely creating project from scratch (default app with only change being square import in pubspec.yaml) gives the other non-module header issue. So completely stuck on ios :(

**Comment by hukid** [comment]
@geekydiamond this is bug in our doc, and we are working on the fix. There is a missing step in the doc that to publish your app, you need sign the SquareInAppPaymentsSDK.framework.  Please let us know if following information help you solve the problem:

Here is the link you can follow: [Step 2: Configure your project to use the In-App Payments SDK](https://docs.connect.squareup.com/payments/in-app-payments-sdk/build-on-ios#step-2-configure-your-project-to-use-the-in-app-payments-sdk)

And example has that configuration correctly:
![screen shot 2019-01-30 at 10 34 25 am](https://user-images.githubusercontent.com/10461017/52003951-cd456d00-247a-11e9-8922-9844b54d4ab0.png)

**Comment by geekydiamond** [comment]
This worked. Big thanks for your quick assistance :)

**Comment by JohnMAustin78** [comment]
Issue will be fixed in the getting started doc with the next update we publish.

**Comment by muhammad-asim786** [comment]
Please someone help try a lot but still facing the issue
![Uploading Screenshot 2024-09-25 at 1.57.38 PM.png…]()
