### ISSUE TITLE
when add card, report error code:unexpected

### ISSUE THREAD

**Issue by Jason-IUVO** [square/in-app-payments-flutter-plugin#224]
When entering the page where the card is added, the pop-up prompt is shown in the figure.
<img width="338" alt="p" src="https://github.com/square/in-app-payments-flutter-plugin/assets/20764827/f1d0817b-898a-4c88-8535-8c8dbfdb7b0b">

**Comment by fka3** [comment]
1. This isn't a problem in the plugin, but in the SDK the plugins wraps.  Issues with that are better sent to Square, either via the BuildWithSquare Slack workspace or via Square's [developer forums](https://developer.squareup.com/forums/).
2. There is nothing here to help anyone _find_ the problem to see what happened.  At a minimum, e would ask for the approximate time of the event, and the merchant or location id to whom it happened.

I would suggest you collect that additional information (date and merchant or location), then report the issue there for assistance.

Sorry the plugin group can't help!

**Comment by atsokha** [comment]
+1 the same

**Comment by plinio-square** [comment]
That's correct, our SDKs only work for the countries mentioned above.

**Comment by larsbs** [comment]
In my case, I was getting that error because I was not using a [sandbox card](https://developer.squareup.com/docs/devtools/sandbox/payments#card-not-present-success-state-values) during testing. Running the app on android helped since the error there is clearer.
