### ISSUE TITLE
Autofill for Credit Card Details

### ISSUE THREAD

**Issue by CoderUni** [square/in-app-payments-flutter-plugin#227]
### Describe the functionality you would like to see
Option for users to autofill their credit card details on card entry flow page

### How would this feature make the plugin more useful?
It is very inconvenient for users to manually type their card details every time they want to buy something. Although it is possible to [save the credit card details](https://developer.squareup.com/docs/cards-api/walkthrough-shared-card) for later use, we do not want to force our users to create an account (and provide us their personal details) before they could buy things.

### Additional context
For **Android**, it looks like autofill isn't configured properly. Autofill details for password pops up but not for credit cards:

![square](https://github.com/square/in-app-payments-flutter-plugin/assets/57564335/e190ef30-f7fb-4954-b74c-ff890c9cf40f)

It looks like it could be solved by setting the autofill hint to credit card info: https://developer.android.com/guide/topics/text/autofill-optimize#credit-card-info

For **iOS**, the autofill simply doesn't work even if I turned autofill for credit cards on. Not sure if there is a way to autofill credit cards. Closest I've seen is for [passwords](https://developer.apple.com/documentation/security/

These are all the gathered info I have so far. Thank you so much for your hard work!

**Comment by fka3** [comment]
Thanks for the suggestion.  Square's data privacy group is resistant to the idea... it amounts to trusting someone else (Google and Apple seem trustworthy, but from Square's regulatory compliance they're both "someone else"), so I'm not sure we'll be able to do this in the context of an SDK we promise is regulatory-approved in multiple markets.
