### ISSUE TITLE
Why a location is required to initialize google pay but no location is required for apple pay?

### ISSUE THREAD

**Issue by ggirotto** [square/in-app-payments-flutter-plugin#234]
### Describe your question

Why a location is required to initialize google pay but no location is required for apple pay?

**Comment by Charmis-Square** [comment]
Implementation is slightly different: Apple Pay requires a merchant identifier to be created directly with Apple as seen in [their docs](https://help.apple.com/xcode/mac/9.3/#/deva43983eb7?sub=dev171483d6e), while Google Pay leaves the action of associating a payment to a merchant/location to Square, as seen in the [Tutorial](https://developers.google.com/pay/api/android/guides/tutorial#tokenization). The difference isn’t really up to Square, but to each company implementing payment wallets.
