### ISSUE TITLE
Update Payments SDK iOS and Android libraries

### ISSUE THREAD

**Issue by jweissen** [square/in-app-payments-flutter-plugin#237]
The Square payments SDK for iOS and Android needs to be upgraded to support Mastercard's new certificate by **June 15, 2024**.  See the below email that was sent to all square users:

![Screenshot 2024-04-05 at 11 20 49 AM](https://github.com/square/in-app-payments-flutter-plugin/assets/13473367/29563c59-164f-43b5-a856-ae8e16ca9ccc)

### Additional context
iOS - 1.6.3
Android - 1.6.6

**Comment by plinio-square** [comment]
this should be fixed now https://github.com/square/in-app-payments-flutter-plugin/pull/238
