### ISSUE TITLE
Needs to be updated to support 1.6.3 ios and 1.6.6 android

### ISSUE THREAD

**Issue by Ospnk** [square/in-app-payments-flutter-plugin#242]
### Flutter plugin needs to be updated accordingly to new updates from square developer team
 Flutter plugin needs to be updated accordingly to new updates from square developer team to use version 1.6.3  for ios and version 1.6.6 for android users

**Comment by abdulmoiz02** [comment]
Is version 1.7.8 providing an up-to-date SDK version for Android and iOS?

**Comment by Ospnk** [comment]
no, 1.7.8 provides iOS: 1.6.2 Android: 1.6.5

**Comment by abdulmoiz02** [comment]
<img width="1219" alt="image" src="https://github.com/square/in-app-payments-flutter-plugin/assets/95373039/8af8f072-ecd5-46e4-a65e-1b97cd1d810a">
In their repository, version 1.6.3 is supported for iOS and 1.6.6 for Android. I think they haven't updated the documentation on pub.dev for version 1.7.8.

**Comment by Ospnk** [comment]
thanks, will close this ticket
