### ISSUE TITLE
Namespace not specified

### ISSUE THREAD

**Issue by mitesh77** [square/in-app-payments-flutter-plugin#245]
### Describe the issue
This is the latest Flutter version v3.22.1 with latest square_in_app_payments: ^1.7.9
not working even in an empty project. Facing a Namespace issue can any one have a solution?

 
### Screenshots
![Screenshot 2024-06-06 at 2 19 37 AM](https://github.com/square/in-app-payments-flutter-plugin/assets/38649435/583369f7-14cc-41d0-88ba-4e18e45c6ed1)

**Comment by larsbs** [comment]
@mitesh77 were you able to find a solution?
