### ISSUE TITLE
Not able to find any info about recurring payments (subscriptions)

### ISSUE THREAD

**Issue by yokiran** [square/in-app-payments-flutter-plugin#27]
Are recurring payments (subscriptions) supported in this plugin. If not, can I request the feature?

**Comment by StephenJosey** [comment]
Recurring payments are not built into any of Square APIs currently. You can make recurring payments work on your own by saving a card on file (this plugin would create the nonce, you would pass the nonce to `CreateCustomerCard` endpoint) for a customer and then charging at a later date. You would probably need to set up some kind of scheduled process to make sure they get charged every X days (or whatever it is).
