### ISSUE TITLE
Can't build apk

### ISSUE THREAD

**Issue by tegab** [square/in-app-payments-flutter-plugin#35]
I cannot build apk, but i can debug. please help.. 

thnx

Execution failed for task ':square_in_app_payments:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  D:\Client\Grocerr\grocerr\build\square_in_app_payments\intermediates\res\merged\release\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  D:\Client\Grocerr\grocerr\build\square_in_app_payments\intermediates\res\merged\release\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  D:\Client\Grocerr\grocerr\build\square_in_app_payments\intermediates\res\merged\release\values\values.xml:2949: error: resource android:attr/fontVariationSettings not found.
  D:\Client\Grocerr\grocerr\build\square_in_app_payments\intermediates\res\merged\release\values\values.xml:2950: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

**Comment by tegab** [comment]
please help.. i can't submit my app.

thnx

**Comment by StephenJosey** [comment]
@tegab it sounds like it can't find `dialogCornerRadius`. Is this something you've added to your project? I just tested building a sample Flutter In-App Payment project using `flutter build apk` and it created the apk successfully. Are you doing anything else?

**Comment by tegab** [comment]
> @tegab it sounds like it can't find `dialogCornerRadius`. Is this something you've added to your project? I just tested building a sample Flutter In-App Payment project using `flutter build apk` and it created the apk successfully. Are you doing anything else?

i tried again... still not working









Running Gradle task 'assembleRelease'...







FAILURE: Build failed with an exception.
Running Gradle task 'assembleRelease'...








Running Gradle task 'assembleRelease'...







* What went wrong:
Running Gradle task 'assembleRelease'...







Execution failed for task ':square_in_app_payments:verifyReleaseResources'.
Running Gradle task 'assembleRelease'...







> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
Running Gradle task 'assembleRelease'...







  D:\Client\Grocerr\grocerr\build\square_in_app_payments\intermediates\res\merged\release\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
Running Gradle task 'assembleRelease'...







  D:\Client\Grocerr\grocerr\build\square_in_app_payments\intermediates\res\merged\release\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
Running Gradle task 'assembleRelease'...







  D:\Client\Grocerr\grocerr\build\square_in_app_payments\intermediates\res\merged\release\values\values.xml:2949: error: resource android:attr/fontVariationSettings not found.
Running Gradle task 'assembleRelease'...







  D:\Client\Grocerr\grocerr\build\square_in_app_payments\intermediates\res\merged\release\values\values.xml:2950: error: resource android:attr/ttcIndex not found.
Running Gradle task 'assembleRelease'...







  error: failed linking references.
Running Gradle task 'assembleRelease'...








Running Gradle task 'assembleRelease'...








Running Gradle task 'assembleRelease'...







* Try:
Running Gradle task 'assembleRelease'...







Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
Running Gradle task 'assembleRelease'...








Running Gradle task 'assembleRelease'...







* Get more help at https://help.gradle.org
Running Gradle task 'assembleRelease'...








Running Gradle task 'assembleRelease'...

**Comment by StephenJosey** [comment]
Are you able to build the Flutter example application in this repo?

**Comment by tegab** [comment]
> Are you able to build the Flutter example application in this repo?

i haven't tried the repo yet.  as you can see from my log.. square up is the issue. i have tried deleting all pubs and multiple computer, with the same result.

**Comment by StephenJosey** [comment]
@tegab could you share your app level `build.gradle` file's contents? (This should be the `<flutter_app_directory>/android/app/build.gradle` file).

**Comment by tegab** [comment]
> @tegab could you share your app level `build.gradle` file's contents? (This should be the `<flutter_app_directory>/android/app/build.gradle` file).

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystorePropertiesFile = rootProject.file("key.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))



android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.halpsoft.grocerr"
        minSdkVersion 21
        targetSdkVersion 28
        multiDexEnabled true
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
         multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
      signingConfigs{
        release{
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    //androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.2-alpha01'
    //implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    implementation "com.squareup.sdk.mobile-commerce:mobile-commerce-sdk:0.2"
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.firebase:firebase-core:16.0.7'
    implementation 'com.crashlytics.sdk.android:crashlytics:2.9.9'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.google.guava:guava:27.0.1-android'
    implementation 'androidx.appcompat:appcompat:1.0.0'
    
    
   
   
}
apply plugin: 'com.google.gms.google-services'

**Comment by tegab** [comment]
> @tegab could you share your app level `build.gradle` file's contents? (This should be the `<flutter_app_directory>/android/app/build.gradle` file).

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystorePropertiesFile = rootProject.file("key.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))



android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.halpsoft.grocerr"
        minSdkVersion 21
        targetSdkVersion 28
        multiDexEnabled true
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
         multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
      signingConfigs{
        release{
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    //androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.2-alpha01'
    //implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    implementation "com.squareup.sdk.mobile-commerce:mobile-commerce-sdk:0.2"
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.firebase:firebase-core:16.0.7'
    implementation 'com.crashlytics.sdk.android:crashlytics:2.9.9'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.google.guava:guava:27.0.1-android'
    implementation 'androidx.appcompat:appcompat:1.0.0'
    
    
   
   
}
apply plugin: 'com.google.gms.google-services'

**Comment by StephenJosey** [comment]
Hi @tegab can you please remove the `implementation "com.squareup.sdk.mobile-commerce:mobile-commerce-sdk:0.2"` line? That's an outdated reference that we no longer use. Please let me know if it still doesn't work after that line is removed.

**Comment by tegab** [comment]
Already tried without it

**Comment by StephenJosey** [comment]
Could you also try changing `compileSdkVersion` to 27?

**Comment by tegab** [comment]
> Could you also try changing `compileSdkVersion` to 27?

same error.  I have no idea how to proceed.

**Comment by StephenJosey** [comment]
@tegab sorry to hear that. One more thing to try: could you try changing back to `compileSdkVersion` to 28, but using `targetSdkVersion` to 27?

**Comment by tegab** [comment]
my project is at a stand still.  i have tried every possible route.  if i remove square it will build successfully.  can't build with it. 

* What went wrong:
Execution failed for task ':square_in_app_payments:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  D:\Client\Grocerr\grocerr\build\square_in_app_payments\intermediates\res\merged\release\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  D:\Client\Grocerr\grocerr\build\square_in_app_payments\intermediates\res\merged\release\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  D:\Client\Grocerr\grocerr\build\square_in_app_payments\intermediates\res\merged\release\values\values.xml:2949: error: resource android:attr/fontVariationSettings not found.
  D:\Client\Grocerr\grocerr\build\square_in_app_payments\intermediates\res\merged\release\values\values.xml:2950: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

**Comment by StephenJosey** [comment]
@tegab We've not been able to replicate this issue. Are you able to share a repository of an application where this error is occurring so that we can troubleshoot on our end?

**Comment by tegab** [comment]
> @tegab We've not been able to replicate this issue. Are you able to share a repository of an application where this error is occurring so that we can troubleshoot on our end?

I was able to resolve this issue.  Just in case someone have this problem.  This solution only apply when you upgrade to androidx


change pub cache square up build 
compileSdkVersion 28
targetSdkVersion 28

**Comment by StephenJosey** [comment]
Awesome, thanks for letting us know how you resolved it! Glad you were able to figure it out.

**Comment by xiyulangzi** [comment]
I met exactly same error, but the suggested solution not help as I already have API level 28 but still have same error.
compileSdkVersion 28
targetSdkVersion 28

**Comment by xiyulangzi** [comment]
after further investigation, this issue resolved as below after I double checked my Android X migration has no problem:

in flutter pub-cache, find the square plugin location:
flutter\.pub-cache\hosted\pub.dartlang.org\square_in_app_payments-1.1.0\android\build.gradle

then modify the build.gradle to ensure API level 28 is used for both(they are 27 as released by square team)

    compileSdkVersion 28
        targetSdkVersion 28


then clean and rebuild, all debug and release version working fine now.

Square team might want have a look of this.
