### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by tegab** [square/in-app-payments-flutter-plugin#39]
I am at the last stage of my app.  I have this major issue that i have been ignoring for awhile.  

I can never get canUseGooglePay to true.  My setting is on google_pay_constants.environmentTest.  I have tried on device and simulator, it doesn't matter.  When i run your git, it will come up true.  The difference on mine is, I am on androidx.  This is the last stage to my project.
My squareLocationId and squareApplicationId is set correctly.

 await InAppPayments.initializeGooglePay(
          squareLocationId, google_pay_constants.environmentTest);
      canUseGooglePay = await InAppPayments.canUseGooglePay;

**Comment by tegab** [comment]
Please help...

![Screenshot_1553194778](https://user-images.githubusercontent.com/7483329/54778008-3aeb5b00-4bd9-11e9-88ac-5af8552d987e.png)

**Comment by StephenJosey** [comment]
So just to clarify: you won't be able to create nonces with the Google Pay test environment, only in production. For production, you need to get approved by Google, which you can see the process we lay out here: https://docs.connect.squareup.com/payments/in-app-payments-sdk/digitalwallet/googlepay-setup#step-7-prepare-to-distribute-your-app-in-production

Have you completed those steps already?

**Comment by tegab** [comment]
> So just to clarify: you won't be able to create nonces with the Google Pay test environment, only in production. For production, you need to get approved by Google, which you can see the process we lay out here: https://docs.connect.squareup.com/payments/in-app-payments-sdk/digitalwallet/googlepay-setup#step-7-prepare-to-distribute-your-app-in-production
> 
> Also note that since you're in "Debug" mode, you won't be able to use Google Pay in production. You must sign your APK with a Google approved key, then try it again and let me know if it still doesn't work.
> 
> Have you completed those steps already?

I know that. The issue is I need to demonstrate this to google. I submitted two forms to google. They want me to demonstrate this to them in environmentTest before they can approve it. In test mode, canUseGooglePay = await InAppPayments.canUseGooglePay; never come back to be true on mine. So, it is not functioning correctly.

I am in desparate need, I have already invested alot of time in squareup sdk.

**Comment by tegab** [comment]
![image](https://user-images.githubusercontent.com/7483329/54789609-b14b8580-4bf8-11e9-9778-f3f878522109.png)

**Comment by StephenJosey** [comment]
Understood, thanks for clarifying. Would you be able to provide a stack trace that could provide us an insight of what's going on?

Also just to ensure: you do have GooglePay installed on your device with a card added? If not, it will return `false`. I'm guessing you do since you said you tested with our sample, but just want to make sure.

**Comment by tegab** [comment]
![image](https://user-images.githubusercontent.com/7483329/54790311-4a7b9b80-4bfb-11e9-85cc-39e5b5745738.png)

here is from your original git.. it shows true.  I am not getting error or any indication of an issue.

**Comment by StephenJosey** [comment]
For the sample (where `canUseGooglePay` is true) are you able to successfully get Google Pay to display on the device?

**Comment by tegab** [comment]
> For the sample (where `canUseGooglePay` is true) are you able to successfully get Google Pay to display on the device?

not on mine, it is always false.   If i use the original git from square up it will show up.

**Comment by StephenJosey** [comment]
Did you update your AndroidManifest.xml to include the wallet API? 

https://github.com/square/in-app-payments-flutter-plugin/blob/master/doc/enable-googlepay.md#step-1-update-androidmanifestxml-for-google-pay

**Comment by tegab** [comment]
> Did you update your AndroidManifest.xml to include the wallet API?
> 
> https://github.com/square/in-app-payments-flutter-plugin/blob/master/doc/enable-googlepay.md#step-1-update-androidmanifestxml-for-google-pay

![image](https://user-images.githubusercontent.com/7483329/54791744-d17f4280-4c00-11e9-97cf-44f221b21b2b.png)

yes

**Comment by tegab** [comment]
I just got this resolved.

**Comment by StephenJosey** [comment]
Thanks for confirming @tegab! For anyone else who stumbles upon this:

I was able to repo the issue by moving the
```
 <meta-data
    android:name="com.google.android.gms.wallet.api.enabled"
    android:value="true" />
```

from inside the `<application> ... </application>` tags and putting it at the top next to the Permission requirements. If the `meta-data` tag used by Google pay is not set within the application tags, then you will run into this issue with a pop up saying “This merchant is not enabled for Google Pay.”

**Comment by AlexanderArendar** [comment]
@StephenJosey it would be great to emphasize in the https://github.com/square/in-app-payments-flutter-plugin/blob/master/doc/enable-googlepay.md#step-1-update-androidmanifestxml-for-google-pay that the <meta-data> tag to be added inside the <application> tab but not inside the <application><activity>.
