### ISSUE TITLE
Crash on _makeCardEntryForm

### ISSUE THREAD

**Issue by unmaskedd** [square/in-app-payments-flutter-plugin#43]
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001091411bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001086df735 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000109140d29 -[NSException raise] + 9
	3   SquareInAppPaymentsSDK              0x0000000107de33d1 SQIPAssertApplicationIDExists + 116
	4   SquareInAppPaymentsSDK              0x0000000107dbb285 -[SQIPCardEntryViewController initWithTheme:applicationID:urlRequestExecutor:logger:riskSignalReporter:device:] + 142
	5   SquareInAppPaymentsSDK              0x0000000107dbb1a9 -[SQIPCardEntryViewController initWithTheme:] + 323
	6   square_in_app_payments              0x00000001086a5da0 -[FSQIPCardEntry _makeCardEntryForm] + 96
	7   square_in_app_payments              0x00000001086a40c8 -[FSQIPCardEn<…>
Lost connection to device.

**Comment by unmaskedd** [comment]
Fixed by editing ios runner code and setting squareapplicationid manually

**Comment by unmaskedd** [comment]
But I dont know if thats how its supposed to be

**Comment by StephenJosey** [comment]
Hey @unmaskedd I haven't been able to replicate this. You should be setting the application id in your code like so:
```
Future<void> _initSquarePayment() async {
    await InAppPayments.setSquareApplicationId('APPLICATION_ID');
}
```
But even if you don't set the application id, it shouldn't crash. Would you be able to provide a code snippet of how you're calling this? Also, if you try the example (in the `example` directory) of the plugin, do you get the same crash?

**Comment by jaddoescad** [comment]
same crashes for me too

**Comment by StephenJosey** [comment]
Hi @jaddoescad were you able to resolve this?

**Comment by StephenJosey** [comment]
Closing for now. Please comment if you're still having this issue.
