### ISSUE TITLE
ApplePayPaymentType missing from models.dart

### ISSUE THREAD

**Issue by d3vtoolsmith** [square/in-app-payments-flutter-plugin#45]
ApplePayPaymentType enum class  seems to be missing from models.dart.
It's present in the Example app, but `square_in_app_payments: ^1.1.1` doesn't seem to have it.

**Comment by StephenJosey** [comment]
Hi @d3vtoolsmith can you try running `flutter clean` to see if that resolves the issue? If that doesn't work try removing the package from dependencies in `pubspec.yaml`, and then run `flutter packages get`. Finally, add the package to dependencies again and run `flutter packages get`.

Please let me know if that doesn't resolve your issue.

**Comment by d3vtoolsmith** [comment]
I've just tried both `flutter clean` and remove/readd (with `flutter packages get` for each), and neither one helped.

**Comment by d3vtoolsmith** [comment]
I've also tried adding `square_in_app_payments: ^1.1.1` to a brand new Flutter project, and `ApplePayPaymentType` (and the corresponding `paymentType` parameter on `requestApplePayNonce`) is still missing.

**Comment by hukid** [comment]
@d3vtoolsmith , the new released `1.2.1` should solved the issue, would you please try again?

**Comment by d3vtoolsmith** [comment]
confirmed `1.2.1` fixes this. thank you!
