### ISSUE TITLE
Latin America square in app payments flutter

### ISSUE THREAD

**Issue by darasat** [square/in-app-payments-flutter-plugin#47]
Good day Square team,

First, Your plugin for in app payments it's amazing , congratulations for this great job.

Now I have two questions
Did square in app payments will work in latin America ? For example in Colombia.
(Using cards like  Visa or Mastercard)
Google pay will work in Colombia?

Thank you very much for you answers
Have a great day.
Cheers.

Sincerely,
Diego Ramírez.

**Comment by hukid** [comment]
@darasat Glad to know you like the plugin! 

As of today, you can take payments with square in-app-pyaments SDK in these 5 countries: US, UK, AU, CA, and JP. Note it's the merchant need to be in one of those countries. So if you are taking payment for latin America merchant, you can't do it now.

Google pay with square in-app-payments SDK has the same limitation as card entry.

**Comment by darasat** [comment]
I understand
