### ISSUE TITLE
Requesting permission within card details flow to put card on file

### ISSUE THREAD

**Issue by geekydiamond** [square/in-app-payments-flutter-plugin#48]
Is there an obvious way as part of the plugin to request from the customer whether they are happy for their card details to be put on file?

I have the backend code working, but it feels a little clunky to ask either before card entry, or after payment is taken, whether we can put their card on file for future payments. Would be preferable if a customer could check a box during card data entry to say they are happy to keep it on file.

**Comment by geekydiamond** [comment]
To give more context, we are building an application that allows a customer to pay for an event. They can choose to pay for the event by card and are presented with a list of their existing cards on file (as retrieved via the Customer endpoint).

The customer either selects an existing card or enters a new one.

Assume a customer enters a new one. It seems odd to ask the question 'can we store this new card on file' before the customer enters the card details, so we don't do it at this point.
Customer enters their card details and then the payment is taken. This seems like the optimal point to ask for permission to keep the card on file because the customer can see the details and confirm that this is a card they are happy to have stored on file. However, I don't think flutter devs can influence this step in the flow.
After payment is taken it is at this point we currently request whether the customer is happy for us to store the card on file. There is some mental load at this point to remembering if this is a card you are happy to store, and also a second server call is required here to store the card (rather than it naturally falling into the charge process - i.e.  if they checked the box then first store the card and then charge against the card on file.).

Just looking for suggestions or confirmation that this is the only option.

**Comment by geekydiamond** [comment]
Found that we can't ask for permission to put card on file after payment because the nonce is no longer valid, so have had to put the request before card details are taken.

**Comment by hukid** [comment]
Thanks for the feedback @geekydiamond! We don't support saving a customer's card on file as they typing the card information for payment. So you have to implement a separate workflow to ask customer to explicitly add their card on file for the future payment.

I'll bring your feedback to the team.

**Comment by mikeyyg96** [comment]
@geekydiamond how were you able to get the full card number?

**Comment by geekydiamond** [comment]
I don't get or want the full card number. You can put a card 'on file' with Square using a nonce and store it against the Customer object. This is preferable because Square manage the card information. You can then retrieve cards for the Customer object from Square next time the customer needs to make a payment.
https://developer.squareup.com/docs/api/connect/v2#endpoint-customers-createcustomercard
