### ISSUE TITLE
Extended ui customization

### ISSUE THREAD

**Issue by TatsuUkraine** [square/in-app-payments-flutter-plugin#49]
### Describe the functionality you would like to see
Allow to use in app payment package inside widgets.

Provide ability to hide submit button and expose generate token method

### How would this feature make the plugin more useful?
Ability to use package inside flutter widget allows to customize appearance,which will make it look more accurate according to app theme. For instance - use app bar according to app theme.

Ability to hide button with exposed token generator method allows to customize submit button according to app theme

**Comment by TatsuUkraine** [comment]
Hello. Any update on this?)

**Comment by StephenJosey** [comment]
No updates to this unfortunately. I've added it to our list of feature requests, but unfortunately we can't guarantee all feature requests.
