### ISSUE TITLE
Exception after hitting "Save" button in the card entry flow

### ISSUE THREAD

**Issue by AlexanderArendar** [square/in-app-payments-flutter-plugin#50]
### Describe the issue
I am trying to integrate the "square_in_app_payments" plugin to my flutter app.
I am able to start the card entry flow and enter all the details in the card entry info view.
But when I hit the "Save" button an exception is printed in the console and the app gets terminated.
The exception is the following one:
```
E/AndroidRuntime(13289): FATAL EXCEPTION: CardResultHandler
E/AndroidRuntime(13289): Process: com.arendaralexander.oauth, PID: 13289
E/AndroidRuntime(13289): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: CardResultHandler
E/AndroidRuntime(13289): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:794)
E/AndroidRuntime(13289): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:684)
E/AndroidRuntime(13289): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:80)
E/AndroidRuntime(13289): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:189)
E/AndroidRuntime(13289): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:155)
E/AndroidRuntime(13289): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
E/AndroidRuntime(13289): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
E/AndroidRuntime(13289): 	at sqip.flutter.internal.CardEntryModule$2.handleEnteredCardInBackground(CardEntryModule.java:86)
E/AndroidRuntime(13289): 	at sqip.internal.CardEntryActivityController$onCardNonceSuccess$1.run(CardEntryActivityController.kt:145)
E/AndroidRuntime(13289): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(13289): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(13289): 	at java.lang.Thread.run(Thread.java:784)
D/ZrHung.AppEyeUiProbe(13289): stop checker.
I/Process (13289): Sending signal. PID: 13289 SIG: 9
```

**Environment (please complete the following information):**
  - platform: Android
  - minSdkVersion 21
  - Android version: 9
  - dev environment: Linux, IntelliJ Idea
  - In-App Payments Plugin version: 1.2.1

flutter doctor -v output:
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Linux, locale en_US.UTF-8)
    • Flutter version 1.7.8+hotfix.3 at /mnt/ssd2/flutter
    • Framework revision b712a172f9 (9 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /home/alex/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /mnt/ssd2/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /mnt/ssd2/android-studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at /mnt/ssd2/IDE/idea-IC-191.7479.19
    • Flutter plugin version 37.0.3
    • Dart plugin version 191.7830

[✓] Connected device (1 available)
    • VKY L29 • 6PM7N17B28000085 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by gstaykov** [comment]
I have reproduced the same problemi with the exmaple app: https://github.com/square/in-app-payments-flutter-plugin/tree/master/example

Just try to pay with the following card:
Card number: 4111 1111 1111 1111
Expiration date: 12/21
CVV: 111

I get this test card details from here: https://developer.squareup.com/docs/testing/test-values?q=test

**Comment by AlexanderArendar** [comment]
Square guys, anyone there?
Would be great to have some feedback. We have an integration feature in the near-future roadmap in one of our projects so I am trying to see if this plugin is something solid which we can use and rely on.

**Comment by havenwood** [comment]
@AlexanderArendar Please join us in our [Square Developer Slack](http://squ.re/slack) community. We'd be happy to help you debug this.

**Comment by mikekono** [comment]
@AlexanderArendar that's for filing the bug report. I think it's related to this flutter issue: https://github.com/flutter/flutter/issues/34993

I'm working on getting a PR out with a fix

**Comment by AlexanderArendar** [comment]
You are awesome, guys. 
I am already there in Slack. 
When the PR comes just let me know and I will help testing.

**Comment by mikekono** [comment]
The fix is in version `1.2.2`. Let me know if you're still seeing the issue @AlexanderArendar

**Comment by gstaykov** [comment]
> The fix is in version `1.2.2`. Let me know if you're still seeing the issue @AlexanderArendar

Yes it is fixed thanks you :) 🥇

**Comment by AlexanderArendar** [comment]
Thanks, @mikekono . It works and I am very happy of this :)

**Comment by shajedulislam** [comment]
@havenwood I am facing this problem in android only. I am using the latest flutter and square plugin version.
