### ISSUE TITLE
Is it possible to have three way payments?

### ISSUE THREAD

**Issue by mikeyyg96** [square/in-app-payments-flutter-plugin#58]
### Describe the functionality you would like to see
I want a user to user transaction with a percentage coming to me.

### How would this feature make the plugin more useful?
It would be useful for apps that want the users to have a source of income.

### Additional context
Anyone know if there is already a way to do this, or is it something that should be added?

**Comment by hukid** [comment]
I see, the In-App Payments SDK helps to exchange a secure token (nonce) from credit card information, then you can use this token(nonce) to take payment on the server side with our Payments API.

Your question is more about the server side payments logic, which you can find more information here: https://developer.squareup.com/docs/payments-api/take-payments-and-collect-fees

Please let me know if you don't see anything helpful.
