### ISSUE TITLE
SCA support

### ISSUE THREAD

**Issue by geekydiamond** [square/in-app-payments-flutter-plugin#59]
Please advise how to use the plugins in an SCA compliant way. I cannot find verifyBuyer() method on the API so am unsure how to get the verification code required to complete a transaction.

**Comment by geekydiamond** [comment]
That’s useful to know. The deadline is 14th September. Is it fair to assume this will be released before then otherwise our payments on our platform will stop working :s

**Comment by geekydiamond** [comment]
Oh, amazing, thank you for that information. I’ll stop panicking now lol

**Comment by Damandroid** [comment]
Phewww just had a mild heart attack reading the post about SCA's original deadline, but feeling better now. Following this as I am in same boat as geekyDiamond

**Comment by geekydiamond** [comment]
I saw the notice that the sdks have been upgraded to include SCA support. Any news on when this will be available in the Flutter plugin?

**Comment by havenwood** [comment]
@geekydiamond The PR to add support has been opened in #77, which just needs to be merged and released.

**Comment by havenwood** [comment]
Just an update that #77 has been merged.

**Comment by StephenJosey** [comment]
Closing this, since it now exists :).
