### ISSUE TITLE
Flutter Web

### ISSUE THREAD

**Issue by jodymac** [square/in-app-payments-flutter-plugin#61]
General Question.  Do you have any details regarding this plugin for when Flutter Web becomes plugin ready?  I'm looking forward to using flutter web and would like to sell off that site.

**Comment by StephenJosey** [comment]
Hi @jodymac unfortunately we don't have an ETA on when (or even if) this will be released. We're definitely glad you're interested, and will update this if we get to the point where we're publicly talking about.

**Comment by ReniDelonzek** [comment]
I am also very interested in pluggin support for web / desktop

**Comment by thachnb85** [comment]
We're also looking for this flutter web support.

**Comment by senordonfelipe** [comment]
Are there any updates for this? Could you also please remove the WEB tag from[ pub.dev](https://pub.dev/packages/square_in_app_payments) to avoid confusion, if its not yet supported?

**Comment by carman247** [comment]
Need this plugin for web!

**Comment by jacobpedd** [comment]
Also need this plugin for the web!

**Comment by topilski** [comment]
Hello, any updates?

**Comment by Zizico2** [comment]
Is this planned? This would be awesome for my use case.

**Comment by AlexanderArendar** [comment]
We have tried to run our flutter app for web, and everything works fine except for the payment. Would be really great if Square supports this plugin for WEB platform as well.

**Comment by kulveersingh** [comment]
Any update on web support ?

**Comment by juliavi** [comment]
Very interested in this! this would be major

**Comment by T3Drones** [comment]
This would be very helpful

**Comment by jonorozcoc** [comment]
Any updates on this?

**Comment by Prayer-RecycleSmart** [comment]
any update or timeline? 
Thanks so much guys

**Comment by jihun-alchera** [comment]
need for the web...ㅠㅠ

**Comment by jihun-alchera** [comment]
need for web

**Comment by KSingh1980** [comment]
Any update on it?

**Comment by Capybara92** [comment]
Any update on it?
 I'm looking forward to using flutter web.

**Comment by jpetro416** [comment]
Any update on this? We need flutter web support!

**Comment by rashinagpal** [comment]
Any update on Flutter web support? otherwise, we need to change our payment service soon.

**Comment by arslankaleem7229** [comment]
Any updates about flutter web support ?

**Comment by hukid** [comment]
There is no near future plan to support flutter web for now. Square does have a separate web payment solution, please check more information here: https://developer.squareup.com/docs/web-payments/overview.

**Comment by jonorozcoc** [comment]
Can you add a wont-fix label to the issue? With that people will know it won't be implemented

**Comment by gsmcdonald** [comment]
I'm also interested in this.
