### ISSUE TITLE
Unable to test Square Example app with Sandbox Application Id

### ISSUE THREAD

**Issue by MattL-NZ** [square/in-app-payments-flutter-plugin#63]
### Describe the issue
When testing with the Square example app, I am getting an error when using the sandbox application id.
  
  Here is the issue:
  ```
Something went wrong. Please contact the developer of this application and provide them with this error code: card_entry_unauthorized.
  ```

### To Reproduce
  Steps to reproduce the issue.
  1. Download the example app
  2. Add your sandbox application ID into the main.dart file
  3. Add default location ID into the main.dart file.

### Expected behavior
 I would expect this to generate a nonce we can use to test payments.

### Flutter Doctor
```
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17134.950], locale en-NZ)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.37.1)
[√] Connected device (1 available)

• No issues found!
```

Could this be happening because I am located in New Zealand? Is in app payments supported in NZ?

**Comment by hukid** [comment]
@MattL-NZ the IAP SDK starts support our new sandbox  in version `1.2.0`, are you using this version for both of your iOS and Android build?

**Comment by okenshields** [comment]
@MattL-NZ , also to confirm, are you using the test credit card mentioned [here](https://developer.squareup.com/docs/testing/test-values#test-credit-card)?

**Comment by okenshields** [comment]
@inaminute, we just merged a change into master branch earlier this week to support sandbox. PR here: https://github.com/square/in-app-payments-flutter-plugin/pull/64 . Will update flutter package soon.

**Comment by MattL-NZ** [comment]
Thanks @okenshields. I'm not using Square anymore as I only realised half way through my development that you don't support payments in New Zealand.
