### ISSUE TITLE
SDK uses legacy v1 or v2 Square API?

### ISSUE THREAD

**Issue by tonydiaz** [square/in-app-payments-flutter-plugin#66]
### Describe your question
I'm trying to understand if this SDK uses legacy v1 or v2 Square API

When I enter my v2 sandbox APPLICATION_ID I get this response on the client mobile application
<img width="291" alt="Screen Shot 2019-09-13 at 4 36 00 PM" src="https://user-images.githubusercontent.com/7145340/64893255-97897900-d644-11e9-9e18-afc4644acb0a.png">

When I enter the Legacy Sandbox Application ID the request goes from the client to the server. I do get another error on the server but that is a different issue:
<img width="310" alt="Screen Shot 2019-09-13 at 5 16 00 PM" src="https://user-images.githubusercontent.com/7145340/64895329-349ae080-d64a-11e9-9a84-8b338577556a.png">

The only place I enter my application ID is in the following function
```js
  Future<void> _initSquarePayment() async {
     await InAppPayments.setSquareApplicationId('APPLICATION_ID');
  }
```

**Comment by StephenJosey** [comment]
Hey @tonydiaz so it actually depends on the versions of the SDK you're using. Android and iOS use the new sandbox tokens on SDK 1.2, however legacy sandbox should work for older ones (which it sounds like you're on the older one since it got past the app id error).

Are you using the heroku quick-start server? If so, could you put the output of the logs on your server when using the legacy sandbox app id? It sounds like somethings going wrong on the backend when it's creating the charge request.

**Comment by tonydiaz** [comment]
I'm using  `square_in_app_payments: ^1.1.0`

Says this in the README
```
The Flutter plugin for Square In-App Payments SDK is a wrapper for the native Android and iOS SDKs and supports the following native In-App Payments SDK versions:

    iOS: 1.1.1
    Android: 1.1.0
```

I'm not using heroku. I took the same code and placed it in firebase function. I get this error in the logs are you looking for more? 
```
>  [Error] Status:404, Messages: [
>    {
>      "code": "NOT_FOUND",
>      "detail": "Card nonce not found",
>      "category": "INVALID_REQUEST_ERROR"
>    }
>  ]

```

**Comment by StephenJosey** [comment]
That's what we're looking for! So it sounds like the `nonce` that you receive in the in app payments plugin isn't making it to your server, or you're not retrieving it. Basically that error means that in the `Charge` request to Square, there was no `card_nonce` which is required because that's how we know what card to charge. Can you confirm you're receiving the nonce in firebase by printing it out?

**Comment by tonydiaz** [comment]
The request body has 
```
{"nonce":"cnon:CBASEDJRuW0yUbHLiUNDyDRpayXXXX"}
```

I removed the last 4 characters in case I should post it.

**Comment by tonydiaz** [comment]
@StephenJosey Any thoughts. The nonce is received on the server-side.

**Comment by StephenJosey** [comment]
Hey @tonydiaz sorry for the delay here. That seems correct to me. One more thing to look out for - are you using the same access token on the server-side that corresponds to the application id that created the nonce?

**Comment by tonydiaz** [comment]
@StephenJosey thank you for the response. I'm using the legacy application ID and legacy access token. I was using the v2 access token on the server-side. 

I now see:
```
>  [Error] Status:401, Messages: [
>    {
>      "category": "AUTHENTICATION_ERROR",
>      "code": "UNAUTHORIZED",
>      "detail": "This request could not be authorized."
>    }
>  ]
```

**Comment by StephenJosey** [comment]
Hm, now we seem to be moving backwards :(. Unauthorized implies the access token is incorrect. On the server-side, can you confirm that you're using `squareup.com...` instead of `squareupsandbox.com...`? The latter only works with the new sandbox (not the legacy sandbox). Sorry for the confusion here.

**Comment by tonydiaz** [comment]
Yes, I was using `https://connect.squareupsandbox.com`. 

After switching to `https://connect.squareup.com` I'm back at:
```
>  [Error] Status:404, Messages: [
>    {
>      "code": "NOT_FOUND",
>      "detail": "Card nonce not found",
>      "category": "INVALID_REQUEST_ERROR"
>    }
>  ]
```
Server-side code:
```js
let oauth2 = defaultClient.authentications["oauth2"];
oauth2.accessToken = <legacySandboxAccessToken>;

// Use API_BASE_PATH to switch between sandbox env and production env
// sandbox: https://connect.squareupsandbox.com
// production: https://connect.squareup.com
defaultClient.basePath = "https://connect.squareup.com"; 

const paymentsApi = new PaymentsApi();
const ordersApi = new OrdersApi();
const locationsApi = new LocationsApi();
const app = express();

app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());


app.post("/chargeForCookie", async (request, response) => {
  const requestBody = request.body;

  console.log("requestbody", JSON.stringify(requestBody));

  try {
    const locations = await locationsApi.listLocations();
    const locationId = locations.locations[0].id;
    console.log("locationID", locationId);
    const createOrderRequest = {
      idempotency_key: crypto.randomBytes(12).toString("hex"),
      order: {
        line_items: [
          {
            name: "Cookie 🍪",
            quantity: "1",
            base_price_money: {
              amount: 100,
              currency: "USD"
            }
          }
        ]
      }
    };
    const order = await ordersApi.createOrder(locationId, createOrderRequest);
    console.log("order :", order);
    const createPaymentRequest = {
      idempotency_key: crypto.randomBytes(12).toString("hex"),
      source_id: requestBody.nonce,
      amount_money: {
        ...order.order.total_money
      },
      order_id: order.order.id,
      autocomplete: true
    };

    console.log("createPaymentRequest :", createPaymentRequest);
    const createPaymentResponse = await paymentsApi.createPayment(
      createPaymentRequest
    );

    console.log(createPaymentResponse.payment);

    response.status(200).json(createPaymentResponse.payment);
  } catch (e) {
    delete e.response.req.headers;
    delete e.response.req._headers;
    console.log("e :", e);
    console.log(
      `[Error] Status:${e.status}, Messages: ${JSON.stringify(
        JSON.parse(e.response.text).errors,
        null,
        2
      )}`
    );

    const { errors } = JSON.parse(e.response.text);

    switch (errors[0].code) {
      case "UNAUTHORIZED":
        response.status(401).send({
          errorMessage:
            "Server Not Authorized. Please check your server permission."
        });
        break;
      case "GENERIC_DECLINE":
        response.status(400).send({
          errorMessage: "Card declined. Please re-enter card information."
        });
        break;
      case "CVV_FAILURE":
        response.status(400).send({
          errorMessage: "Invalid CVV. Please re-enter card information."
        });
        break;
      case "ADDRESS_VERIFICATION_FAILURE":
        response.status(400).send({
          errorMessage: "Invalid Postal Code. Please re-enter card information."
        });
        break;
      case "EXPIRATION_FAILURE":
        response.status(400).send({
          errorMessage:
            "Invalid expiration date. Please re-enter card information."
        });
        break;
      case "INSUFFICIENT_FUNDS":
        response.status(400).send({
          errorMessage:
            "Insufficient funds; Please try re-entering card details."
        });
        break;
      case "CARD_NOT_SUPPORTED":
        response.status(400).send({
          errorMessage:
            "	The card is not supported either in the geographic region or by the MCC; Please try re-entering card details."
        });
        break;
      case "PAYMENT_LIMIT_EXCEEDED":
        response.status(400).send({
          errorMessage:
            "Processing limit for this merchant; Please try re-entering card details."
        });
        break;
      case "TEMPORARY_ERROR":
        response.status(500).send({
          errorMessage: "Unknown temporary error; please try again;"
        });
        break;
      default:
        response.status(400).send({
          errorMessage:
            "Payment error. Please contact support if issue persists."
        });
        break;
    }
  }
});

```

**Comment by tonydiaz** [comment]
Is it ok that is uses the v2 API for the legacy ID and token? 

```
      error:
>        { Error: cannot POST /v2/payments (404)
>            at Response.toError (/firebase-square/functions/node_modules/superagent/lib/node/response.js:94:15)
>            at ResponseBase._setStatusProperties (/firebase-square/functions/node_modules/superagent/lib/response-base.js:123:16)
>            at new Response (/firebase-square/functions/node_modules/superagent/lib/node/response.js:41:8)
>            at Request._emitResponse (/firebase-square/functions/node_modules/superagent/lib/node/index.js:752:20)
>            at parser (/firebase-square/functions/node_modules/superagent/lib/node/index.js:916:38)
>            at IncomingMessage.res.on (/firebase-square/functions/node_modules/superagent/lib/node/parsers/json.js:19:7)
>            at IncomingMessage.emit (events.js:187:15)
>            at endReadableNT (_stream_readable.js:1094:12)
>            at process._tickCallback (internal/process/next_tick.js:63:19)
>          status: 404,
>          text:
>           '{"errors": [{"code": "NOT_FOUND","detail": "Card nonce not found","category": "INVALID_REQUEST_ERROR"}]}\n',
>          method: 'POST',
>          path: '/v2/payments' },
```

**Comment by StephenJosey** [comment]
Ah, actually, now that you point it out I think you're right, sorry for the confusion. I believe Payments API will not work with legacy sandbox nonces. I think the easiest path forward would be upgrading to use the In-App Payments 1.2 (which as of 9 days ago the SDK is using 1.2, so you should just be able to pull the latest changes), and switch to the new sandbox app id and sandbox access token.

I'll leave this open until you confirm that this was successful, but please let me know if you have any other questions.

**Comment by tonydiaz** [comment]
I upgraded to `square_in_app_payments: ^1.2.0` and switched to the v2 sandbox application ID and access token. Also switched to the  `https://connect.squareupsandbox.com` path and it worked. 

Thanks so much, wouldn't have figured this out without your help!

**Comment by griotdonation** [comment]
> Yes, I was using `https://connect.squareupsandbox.com`.
> 
> After switching to `https://connect.squareup.com` I'm back at:
> 
> ```
> >  [Error] Status:404, Messages: [
> >    {
> >      "code": "NOT_FOUND",
> >      "detail": "Card nonce not found",
> >      "category": "INVALID_REQUEST_ERROR"
> >    }
> >  ]
> ```
> 
> Server-side code:
> 
> ```js
> let oauth2 = defaultClient.authentications["oauth2"];
> oauth2.accessToken = <legacySandboxAccessToken>;
> 
> // Use API_BASE_PATH to switch between sandbox env and production env
> // sandbox: https://connect.squareupsandbox.com
> // production: https://connect.squareup.com
> defaultClient.basePath = "https://connect.squareup.com"; 
> 
> const paymentsApi = new PaymentsApi();
> const ordersApi = new OrdersApi();
> const locationsApi = new LocationsApi();
> const app = express();
> 
> app.use(bodyParser.urlencoded({ extended: false }));
> app.use(bodyParser.json());
> 
> 
> app.post("/chargeForCookie", async (request, response) => {
>   const requestBody = request.body;
> 
>   console.log("requestbody", JSON.stringify(requestBody));
> 
>   try {
>     const locations = await locationsApi.listLocations();
>     const locationId = locations.locations[0].id;
>     console.log("locationID", locationId);
>     const createOrderRequest = {
>       idempotency_key: crypto.randomBytes(12).toString("hex"),
>       order: {
>         line_items: [
>           {
>             name: "Cookie 🍪",
>             quantity: "1",
>             base_price_money: {
>               amount: 100,
>               currency: "USD"
>             }
>           }
>         ]
>       }
>     };
>     const order = await ordersApi.createOrder(locationId, createOrderRequest);
>     console.log("order :", order);
>     const createPaymentRequest = {
>       idempotency_key: crypto.randomBytes(12).toString("hex"),
>       source_id: requestBody.nonce,
>       amount_money: {
>         ...order.order.total_money
>       },
>       order_id: order.order.id,
>       autocomplete: true
>     };
> 
>     console.log("createPaymentRequest :", createPaymentRequest);
>     const createPaymentResponse = await paymentsApi.createPayment(
>       createPaymentRequest
>     );
> 
>     console.log(createPaymentResponse.payment);
> 
>     response.status(200).json(createPaymentResponse.payment);
>   } catch (e) {
>     delete e.response.req.headers;
>     delete e.response.req._headers;
>     console.log("e :", e);
>     console.log(
>       `[Error] Status:${e.status}, Messages: ${JSON.stringify(
>         JSON.parse(e.response.text).errors,
>         null,
>         2
>       )}`
>     );
> 
>     const { errors } = JSON.parse(e.response.text);
> 
>     switch (errors[0].code) {
>       case "UNAUTHORIZED":
>         response.status(401).send({
>           errorMessage:
>             "Server Not Authorized. Please check your server permission."
>         });
>         break;
>       case "GENERIC_DECLINE":
>         response.status(400).send({
>           errorMessage: "Card declined. Please re-enter card information."
>         });
>         break;
>       case "CVV_FAILURE":
>         response.status(400).send({
>           errorMessage: "Invalid CVV. Please re-enter card information."
>         });
>         break;
>       case "ADDRESS_VERIFICATION_FAILURE":
>         response.status(400).send({
>           errorMessage: "Invalid Postal Code. Please re-enter card information."
>         });
>         break;
>       case "EXPIRATION_FAILURE":
>         response.status(400).send({
>           errorMessage:
>             "Invalid expiration date. Please re-enter card information."
>         });
>         break;
>       case "INSUFFICIENT_FUNDS":
>         response.status(400).send({
>           errorMessage:
>             "Insufficient funds; Please try re-entering card details."
>         });
>         break;
>       case "CARD_NOT_SUPPORTED":
>         response.status(400).send({
>           errorMessage:
>             "	The card is not supported either in the geographic region or by the MCC; Please try re-entering card details."
>         });
>         break;
>       case "PAYMENT_LIMIT_EXCEEDED":
>         response.status(400).send({
>           errorMessage:
>             "Processing limit for this merchant; Please try re-entering card details."
>         });
>         break;
>       case "TEMPORARY_ERROR":
>         response.status(500).send({
>           errorMessage: "Unknown temporary error; please try again;"
>         });
>         break;
>       default:
>         response.status(400).send({
>           errorMessage:
>             "Payment error. Please contact support if issue persists."
>         });
>         break;
>     }
>   }
> });
> ```

Hi, where exactly did you find the server side code?

**Comment by StephenJosey** [comment]
Hi @griotdonation, we have a sample backend server here: https://github.com/square/in-app-payments-server-quickstart

**Comment by havenwood** [comment]
@griotdonation This video shows another take on a backend in Ruby: https://youtu.be/gnyVOETIaEA

The principle is the same in whatever backend language you'd like to use. Send the nonce and ids of what's being purchased to your backend. The backend secures your Square access token and is your pricing point of truth. For charging a card, the backend sends the card token nonce and amount of money to the Square API and returns the result of the attempted payment back to your Flutter app payment flow.

**Comment by griotdonation** [comment]
> Hi @griotdonation, we have a sample backend server here: https://github.com/square/in-app-payments-server-quickstart

I've set up my heroku backend. I am able to successfully charge $1 in my mobile app. however, I would like change the amount charged to $10.  On my Square dash board, in transaction details I see the charge for the Cookie 🍪 item. Im not sure where on my backend i can find the server side code to change charge amount. really appreciate any help on this matter.

**Comment by griotdonation** [comment]
> sample backend server

after downloading sample backend server code, where would I place this code? Sorry new to part of coding.

**Comment by StephenJosey** [comment]
@griotdonation the amount can be found on line 126: https://github.com/square/in-app-payments-server-quickstart/blob/master/index.js#L126. The backend sample is just that - an example, and so ultimately you should change it to your needs (ie probably want to charge for something other than a cookie :)).

**Comment by griotdonation** [comment]
> @griotdonation the amount can be found on line 126: https://github.com/square/in-app-payments-server-quickstart/blob/master/index.js#L126. The backend sample is just that - an example, and so ultimately you should change it to your needs (ie probably want to charge for something other than a cookie :)).

Hi Stephen

Thanks so much for your replies. My issue is where do I place this quick start server code after downloading? Do I place files, in my flutter project? Heroku? Square-Devolper?  Thanks in advance for you response.

**Comment by StephenJosey** [comment]
Ah, I see sorry for the confusion. The code is meant to be placed on the backend; the example specifically is a Node JS backend. For testing, you can definitely throw it on Heroku, or if you want you can also fire up a Node JS server on your own computer for local testing. For that, you would need to look up for your particular OS (mac/windows/linux etc), to see how to install Node on your own computer. We do mention how to start the server on a localhost in the README: https://github.com/square/in-app-payments-server-quickstart#start-localhost-server

For production, you probably want to pay for a hosting provider to upload your code to so that it's available 24/7 and has support etc. 

We have some basics in our docs about this here that may explain it better than I can: https://developer.squareup.com/docs/working-with-apis/frontend-versus-backend

For additional help, I would suggest reaching out to our developer slack community, which may be a bit faster in response: https://squ.re/2Hks3YE

**Comment by griotdonation** [comment]
> Ah, I see sorry for the confusion. The code is meant to be placed on the backend; the example specifically is a Node JS backend. For testing, you can definitely throw it on Heroku, or if you want you can also fire up a Node JS server on your own computer for local testing. For that, you would need to look up for your particular OS (mac/windows/linux etc), to see how to install Node on your own computer. We do mention how to start the server on a localhost in the README: https://github.com/square/in-app-payments-server-quickstart#start-localhost-server
> 
> For production, you probably want to pay for a hosting provider to upload your code to so that it's available 24/7 and has support etc.
> 
> We have some basics in our docs about this here that may explain it better than I can: https://developer.squareup.com/docs/working-with-apis/frontend-versus-backend
> 
> For additional help, I would suggest reaching out to our developer slack community, which may be a bit faster in response: https://squ.re/2Hks3YE

Thank you so so much!! This was very helpful!!  : )
