### ISSUE TITLE
Automatically send receipts when payments are successful

### ISSUE THREAD

**Issue by harunB10** [square/in-app-payments-flutter-plugin#70]
I want to send email receipt to my customers using API. Is it possible with Square?

**Comment by StephenJosey** [comment]
Unfortunately, there is no API for sending out receipts. You can retrieve the `receipt_url` from V1 Payments API: https://developer.squareup.com/docs/api/connect/v2#type-v1payment but there is no way to actually email it using our APIs, you would need to build the functionality out yourself.
