### ISSUE TITLE
Any plan to include 'Add to apple wallet' features for reward cards?

### ISSUE THREAD

**Issue by sohitEngg** [square/in-app-payments-flutter-plugin#71]
Currently I am not seeing any example source code where I can use 'Add to apple wallet' feature in order to add reward cards into wallet.

Let me know if I am missing any article here or it is yet to add in the plugin. 

Please add one if it is not yet added, I have a similar requirement in my ongoing assignment.

Thank you very much in advance.

**Comment by StephenJosey** [comment]
This is not currently possible, but thank you for the feedback.

**Comment by egorikem** [comment]
Why is that? Can't you call a native dialog for that from Flutter environment?

**Comment by CharmisG** [comment]
Thank you for your feedback. We have shared the feedback with our team.
