### ISSUE TITLE
Can in-app payments be configured for purchase to merchants? 

### ISSUE THREAD

**Issue by tonydiaz** [square/in-app-payments-flutter-plugin#73]
### Describe your question
Can this plugin be configured to handle purchases to a Merchant's account? 

Right now you need to configure the plugin using the APPLICATION ID. I wanted to see if you can use the Merchant's access token to process payments from customers? 

If not, any suggestions on an alternative?

**Comment by tonydiaz** [comment]
Perhaps I would pass the Merchant's access token to the `chargeCard` method and then use that on the payment processing on the server?

**Comment by StephenJosey** [comment]
You would use the OAuth API to ask the merchant for permission to access their account. If they approve, then you would use the OAuth API to also generate a unique OAuth access token for their account, which you can use to call `chargeCard` as you mentioned. Please see what OAuth can do here: https://developer.squareup.com/docs/oauth-api/what-it-does and let me know if you have any questions.

**Comment by tonydiaz** [comment]
Thanks @StephenJosey. I have another part of the application for a merchant to OAuth.  Is it ok to pass the access token in the body of the post request to process payments? https://github.com/square/in-app-payments-flutter-plugin/blob/master/example/lib/transaction_service.dart#L33

**Comment by tonydiaz** [comment]
I figured out a way to do this. I think this can be closed.
