### ISSUE TITLE
InAppPayments.startCardEntryFlow

### ISSUE THREAD

**Issue by haneensaadeh1994** [square/in-app-payments-flutter-plugin#74]
How do I set the price and currency or other details in : 
InAppPayments.startCardEntryFlow method ?!!

and Where does the transaction appear exactly in dashboard??
`  

    await InAppPayments.setSquareApplicationId('my_key');

    await InAppPayments.startCardEntryFlow(

        onCardNonceRequestSuccess: (CardDetails result) async {

          try {

            InAppPayments.completeCardEntry(

                onCardEntryComplete:   (){

              print('OKAY!');

            });

           var chargeResult =  PaymentRepository.actuallyMakeTheCharge(result.nonce);

           print('Success');
           print(chargeResult);
           if(chargeResult != 'Success!') throw new StateError(chargeResult);

          } catch (ex) {
            print('there are problem!');
            InAppPayments.showCardNonceProcessingError(ex.toString());
          }
        },
        onCardEntryCancel: (){
          print('CANCEL!');
        },
        collectPostalCode: false);
`

**Comment by StephenJosey** [comment]
You don't set the price on in the In App Payments SDK. This SDK is solely for generating a nonce which can then be used on a backend server to call `CreatePayment`, which is what will take a price. Once you create the payment (after calling `CreatePayment`), if the payment was successful it will show up under the Square Dashboard -> Transactions page.
