### ISSUE TITLE
Apple Pay & Google Pay for In-App purchases in UK

### ISSUE THREAD

**Issue by geekydiamond** [square/in-app-payments-flutter-plugin#75]
In a support request I asked about Apple Pay & Google Pay not working in the UK. I was told it wasn't available internationally yet.

Also, the plugin incorrectly gives a success from this code check:
  await InAppPayments.initializeApplePay(appleMerchantId);
  canUseApplePay = await InAppPayments.canUseApplePay
So it seems it is not internationally aware.

Could we track progress of international support via this ticket (unless it's already done, in which case I'll do a little happy dance!)

**Comment by StephenJosey** [comment]
Hi @geekydiamond, sorry for the delay here. The international availability of digital wallets is still not available, and unfortunately we do not have an ETA on when it will be. We will definitely update this thread when it is released.

On your second note, the digital wallet checks within In-App Payments SDK will simply check to see if the device is able to use the digital wallet. The limitation of the digital wallets being available in the United States are on the Square account side, not the buyer's side. Thus, if the seller has a Square account in the United States, a buyer from the UK could still use the digital wallet.
