### ISSUE TITLE
How can I change the locale or language of the card entry screen??

### ISSUE THREAD

**Issue by henrychancat** [square/in-app-payments-flutter-plugin#76]
I need to show Japanese language of the card entry screen and Japan is currently a supporting region of Square payment service, so I would like to how to archive this. If not, would the team please help to make some enhancements of locale and language issue. Thank you.

**Comment by StephenJosey** [comment]
Hi @henrychancat sorry for the delay in response. If the phone's language is set to Japanese, it should translate to Japanese within the card entry screen. Please let me know if that's not the case, though!

**Comment by and2long** [comment]
<img src="https://github.com/square/in-app-payments-flutter-plugin/assets/17178272/bf7295ec-4615-44cc-97b6-4c995a78f1e7" width=250/>
<img src="https://github.com/square/in-app-payments-flutter-plugin/assets/17178272/e592d8cf-e5ed-4483-9263-616255e3238b" width=250/>

Hi @StephenJosey I have hange my phone's language to Japanese, but my Add Card Page is still displayed in english.
Did I miss something else?
