### ISSUE TITLE
android.support.annotation does not exist import android.support.annotation.Nullable;

### ISSUE THREAD

**Issue by sgehrman** [square/in-app-payments-flutter-plugin#86]
Since the current in-app-payments-flutter-plugin is completely broken on Flutter 1.12, I tried to use branch jessiedlcs/UpdatePlugin.

but that branch gives other errors.  I'm on Flutter 1.12 and I can't downgrade flutter as many other packages in my app require 1.12.

It would be good it you could fix this ASAP.  Unfortunately Stripe is just as buggy and painful to use otherwise I would switch.

This package is part of the Android support library which is no longer maintained. The support library has been superseded by AndroidX which is part of Jetpack. We recommend using the AndroidX libraries

Launching lib/main.dart on HD1905 in debug mode...
/home/steve/google/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
                        ^
1 warning
/home/steve/google/flutter/.pub-cache/git/in-app-payments-flutter-plugin-47f4f75882e0332366897b4b97b6235c865aeb65/android/src/main/java/sqip/flutter/CallHandler.java:13: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/home/steve/google/flutter/.pub-cache/git/in-app-payments-flutter-plugin-47f4f75882e0332366897b4b97b6235c865aeb65/android/src/main/java/sqip/flutter/CallHandler.java:14: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/home/steve/google/flutter/.pub-cache/git/in-app-payments-flutter-plugin-47f4f75882e0332366897b4b97b6235c865aeb65/android/src/main/java/sqip/flutter/internal/CardEntryModule.java:24: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/home/steve/google/flutter/.pub-cache/git/in-app-payments-flutter-plugin-47f4f75882e0332366897b4b97b6235c865aeb65/android/src/main/java/sqip/flutter/internal/GooglePayModule.java:20: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/home/steve/google/flutter/.pub-cache/git/in-app-payments-flutter-plugin-47f4f75882e0332366897b4b97b6235c865aeb65/android/src/main/java/sqip/flutter/CallHandler.java:24: error: cannot find symbol
            @Nullable PluginActivityLink activityLink,
             ^
  symbol:   class Nullable
  location: class CallHandler
/home/steve/google/flutter/.pub-cache/git/in-app-payments-flutter-plugin-47f4f75882e0332366897b4b97b6235c865aeb65/android/src/main/java/sqip/flutter/CallHandler.java:25: error: cannot find symbol
            @NonNull MethodChannel methodChannel) {
             ^
  symbol:   class NonNull
  location: class CallHandler
/home/steve/google/flutter/.pub-cache/git/in-app-payments-flutter-plugin-47f4f75882e0332366897b4b97b6235c865aeb65/android/src/main/java/sqip/flutter/CallHandler.java:36: error: cannot find symbol
    public void setActivityLink (@Nullable PluginActivityLink activityLink) {
                                  ^
  symbol:   class Nullable
  location: class CallHandler
/home/steve/google/flutter/.pub-cache/git/in-app-payments-flutter-plugin-47f4f75882e0332366897b4b97b6235c865aeb65/android/src/main/java/sqip/flutter/internal/CardEntryModule.java:67: error: cannot find symbol
  public CardEntryModule(@Nullable PluginActivityLink activityLink, final MethodChannel channel) {
                          ^
  symbol:   class Nullable
  location: class CardEntryModule
/home/steve/google/flutter/.pub-cache/git/in-app-payments-flutter-plugin-47f4f75882e0332366897b4b97b6235c865aeb65/android/src/main/java/sqip/flutter/internal/CardEntryModule.java:79: error: cannot find symbol
  public void setActivityLink(@Nullable PluginActivityLink activityLink) {
                               ^
  symbol:   class Nullable
  location: class CardEntryModule
/home/steve/google/flutter/.pub-cache/git/in-app-payments-flutter-plugin-47f4f75882e0332366897b4b97b6235c865aeb65/android/src/main/java/sqip/flutter/internal/GooglePayModule.java:63: error: cannot find symbol
  public GooglePayModule(@Nullable PluginActivityLink activityLink, final MethodChannel channel) {
                          ^
  symbol:   class Nullable
  location: class GooglePayModule
/home/steve/google/flutter/.pub-cache/git/in-app-payments-flutter-plugin-47f4f75882e0332366897b4b97b6235c865aeb65/android/src/main/java/sqip/flutter/internal/GooglePayModule.java:72: error: cannot find symbol
  public void setActivityLink(@Nullable PluginActivityLink activityLink){
                               ^
  symbol:   class Nullable
  location: class GooglePayModule
Note: /home/steve/google/flutter/.pub-cache/git/in-app-payments-flutter-plugin-47f4f75882e0332366897b4b97b6235c865aeb65/android/src/main/java/sqip/flutter/SquareInAppPaymentsFlutterPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/steve/google/flutter/.pub-cache/git/in-app-payments-flutter-plugin-47f4f75882e0332366897b4b97b6235c865aeb65/android/src/main/java/sqip/flutter/internal/CardEntryModule.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
11 errors

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':square_in_app_payments:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin cloud_firestore...
The plugin cloud_firestore could not be built due to the issue above.
Exited (sigterm)

**Comment by StephenJosey** [comment]
Thanks for the report. This is still being investigated per https://github.com/square/in-app-payments-flutter-plugin/issues/82.

**Comment by StephenJosey** [comment]
Closing in favor of https://github.com/square/in-app-payments-flutter-plugin/issues/82 - this should be resolved when that issue is resolved (when we support newer Flutter versions).
