### ISSUE TITLE
square_in_app_payments locks built_value version

### ISSUE THREAD

**Issue by AlexanderArendar** [square/in-app-payments-flutter-plugin#87]
We are using square_in_app_payments and built_value plugins in our project.
I've decided to upgrade the built_value plugin from 6.7.1 version to 7.0.9 latest version.
But when I try to do this the following outcome is printed:
```
Because square_in_app_payments 1.3.0 depends on built_value ^6.1.5 and no versions of square_in_app_payments match >1.3.0 <2.0.0, square_in_app_payments ^1.3.0 requires built_value ^6.1.5.
So, because ui_flutter depends on both built_value ^7.0.9 and square_in_app_payments ^1.3.0, version solving failed.
pub get failed (1; So, because ui_flutter depends on both built_value ^7.0.9 and square_in_app_payments ^1.3.0, version solving failed.)
```
1.3.0 is the latest version of Square plugin and it looks like it locks the built_value version and we can't upgrade.

Could you advice?

**Comment by StephenJosey** [comment]
Thanks for reaching out. I don't believe there's currently a way to upgrade the `built_value` version, unfortunately, but I've shared this with the team and they're looking into updating the dependencies. I'll update this thread once I have more information.

**Comment by AlexanderArendar** [comment]
@StephenJosey I've set square_in_app_payments: ^1.5.0 and   built_value: ^7.0.0, built_value_generator: ^7.0.0.

When trying to `flutter pub get` it fails with this message:
```
alex@old-horse:/mnt/sdb/projects/aicamping/ui_flutter_demo$ flutter pub get
Because square_in_app_payments 1.5.0 depends on built_value ^6.1.5 and no versions of square_in_app_payments match >1.5.0 <2.0.0, square_in_app_payments ^1.5.0 requires built_value ^6.1.5.
So, because eventhut depends on both built_value ^7.0.0 and square_in_app_payments ^1.5.0, version solving failed.
```
