### ISSUE TITLE
request_card_nonce_invalid_applicaton_id

### ISSUE THREAD

**Issue by blakete** [square/in-app-payments-flutter-plugin#88]
### Describe the issue

When attempting to add payment processing to my flutter application, allow a customer to add a credit card and initiate a transaction, I was given the following error. I cannot seem to locate others having a similar issue and wanted to reach out. I have a Square developer account and have made an app to obtain an application ID to perform transactions within my app. However, the ID continues to say that it is invalid. Can someone assist me with this and let me know what is going wrong?
   
Here is the log:
  ```
Please contact the developer of this application and provide them with this code: request_card_nonce_invalid_applicaton_id
  ```

### To Reproduce
1. Instantiate the provided class and call the method with a given application ID
2. See if the same issues can be reproduced with your key 

Here the piece of code to reproduce the issue. Other dart classes are able to instantiate this class and then make calls to its functions to perform rudimentary payment processing.
  ```dart
import 'package:square_in_app_payments/models.dart';
import 'package:square_in_app_payments/in_app_payments.dart';

class PaymentProcessing {

  void pay() {
    print('Attempting to process credit card...');
    InAppPayments.setSquareApplicationId("REPLACE-HERE-W/-YOUR-KEY");
    InAppPayments.startCardEntryFlow(
      onCardNonceRequestSuccess: _cardNonceRequestSuccess,
      onCardEntryCancel: _onCardEntryCancel
    );
  }
      
  void _cardNonceRequestSuccess(CardDetails result) {
    print(result.nonce);
    print('success!');
    InAppPayments.completeCardEntry(
      onCardEntryComplete: _cardEntryComplete
    );
  }
            
  void _onCardEntryCancel() {
    print("card entry canceled");
  }

  void _cardEntryComplete() {
    print("card entry complete");
  }
}
 ```

### Expected behavior
 The payment with a mock card to go through and return a nonce to be passed to my backend to handle completion of the transaction.

**Environment:**
  - platform: iOS
  - OS and version: 12
  - dev environment: MacOS
  - In-App Payments Plugin version: 1.1.1

**Comment by havenwood** [comment]
Could you confirm that you're using the "Application ID" from your Developer Portal and not the "Access Token" for the `"REPLACE-HERE-W/-YOUR-KEY"` field?

The Application ID also differs between sandbox and production environments. Are you using the Application ID that corresponds to the environment you're in?

**Comment by StephenJosey** [comment]
Hi @blakeedwards823 were you able to resolve this issue?

**Comment by blakeedwards823** [comment]
> Hi @blakeedwards823 were you able to resolve this issue?

I was not able to. The issue persists.

**Comment by StephenJosey** [comment]
Apologies for the delay here. Would you be willing to share your app id here so we can test?

**Comment by StephenJosey** [comment]
Please feel free to reopen if further help is needed.
