### ISSUE TITLE
There's no entrance to create a new application from Square Dashboard

### ISSUE THREAD

**Issue by XinwenCheng** [square/in-app-payments-flutter-plugin#92]
![](https://user-images.githubusercontent.com/795334/75305686-c6f21200-5881-11ea-9530-5e7e16eab57e.png)

### Describe your question
After sign up and sign in into Square, it turns to Launchpad automatically, is it Dashboard's new name? But I couldn't find out where I can create a new application. Tried on Firefox and Chrome and make sure it not a browser issue.

**Comment by StephenJosey** [comment]
Hey @XinwenCheng thanks for reaching out. If I recall correctly, this is an issue where you had an employee login, but the actual Square account was deleted by the account owner. If you wish to continue using the same email for login, unfortunately you'll need to reach out to Square's general support to help get that fixed: https://squareup.com/help/us/en/

If you don't want to use the email (or don't care), the next best option is creating a new Square account, unfortunately. Apologies for the inconvenience! Let me know if neither of these options work, though. I'll leave this issue open for a bit in case you want to reach back out.
