### ISSUE TITLE
shrinkResource, minifyEnabled and proguard crashes android app after Card Entry Flow

### ISSUE THREAD

**Issue by py-zoid** [square/in-app-payments-flutter-plugin#93]
Android app crashes after card entry flow. Issue only occurs in while running in release mode. I'm using square_in_app_payments 1.2.3 on flutter version 1.9.1+hotfix.6. The card nonce is being generated but reentry to app screen from the card entry screen causes crash.

Flutter Doctor Report:
```
[✓] Flutter (Channel unknown, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G84, locale en-US)
    • Flutter version 1.9.1+hotfix.6 at /Users/M/flutter
    • Framework revision 68587a0916 (6 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/M/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)

• No issues found
```

**Comment by py-zoid** [comment]
Okay, an update!
So, the app crashes on android because of using the shrinkResource, minifyEnabled and useProguard. I commented them out of the release buildType in build.gradle file and it doesn't crash anymore. But my app size has been increased a lot, obviously. So can anyone suggest how I can better solve this issue?

**Comment by StephenJosey** [comment]
Hey @py-zoid apologies for the delay here. Could you try updating to Android SDK 1.3.1 (was released in December), and I believe this issue was resolved in this version. Please see https://github.com/square/in-app-payments-flutter-plugin/blob/master/doc/versioning.md#android how to change the version.
