### ISSUE TITLE
App rejected because Apple Pay button Guidlines

### ISSUE THREAD

**Issue by exgonline** [square/in-app-payments-flutter-plugin#95]
Hi,

I am having my app rejected by Apple, because of the grey colour of the Apple Pay button when disabled. They are saying that it does not meet the guidelines. If Apple Pay is on the device, but no cards added, should I hide the button or just change the color to black!

Thanks in advance.

**Comment by StephenJosey** [comment]
Please see https://developer.apple.com/design/human-interface-guidelines/apple-pay/overview/introduction/ for Apple's guidelines on how they would like the Apple Pay button to appear. I'll discuss with our documentation team to see if we could put this in our documentation as a head's up to developers.

According to their guidelines, if the device is iOS but hasn't set up Apple Pay (no cards), you could show a button for setting it up. Alternatively, I think your next best bet would be to hide it as you suggested.

**Comment by exgonline** [comment]
Thanks for taking the time to reply Stephen. I have decided to show a dialog explaining the user needs to add a card to use this method, as I have already had the app rejected because the reviewer could not find the button!! (Ii use your standard buy sheet!). I'll let you know how things go!

**Comment by StephenJosey** [comment]
Sounds good! Let us know if you have any further questions or concerns.

**Comment by exgonline** [comment]
In the end, I added a setup apple pay button and used some Swift code to open the openpaymentscreen via a methodchannel. App was approved today. :-)

**Comment by StephenJosey** [comment]
Awesome, glad to hear it!

**Comment by AhmedAbouelkher** [comment]
@exgonline 
Can you send the native code you used?
