### ISSUE TITLE
card_entry_sandbox_not_supported

### ISSUE THREAD

**Issue by exgonline** [square/in-app-payments-flutter-plugin#96]
Hi everyone.

I am having an issue when entering real card details. I get the error : card_entry_sandbox_not_supported.
I have checked the application ID is the new production ID and not the sandbox one in the InAppPayments.setSquareApplicationId call.

I have looked and cannot see the sandbox Id in any other locations !

This message appears when pressing save after entering the card details. I get the spinning padlock, then the dialog with the error!

If I enter the sandbox card (4111 111 1111 1111) I get a successful card nonce

I assume that by this point, the app would not have connected to my transaction server?

Any thoughts to point me in the right direction, please.

**Comment by StephenJosey** [comment]
I'm not entirely sure I understand the question. You say you receive `card_entry_sandbox_not_supported` but also say if you enter a sandbox card you get a successful nonce? Only sandbox cards are supported in sandbox (not real, live cards).

You're correct - once you receive the nonce, no payment has happened yet. You would still need to pass to your backend and call `CreatePayment` with the nonce and amount. Let me know if I'm misunderstanding, though.

**Comment by jaydeepw** [comment]
OK. After a long research, I figured out that I have to test my integration using the test çards that are given here.

https://developer.squareup.com/docs/testing/test-values#client-side-testing

However, when my card is successfully added, can I not query a list of cards added using the SDK by me?

I only wish that developers from Square had better written the documentation for integration.

**Comment by StephenJosey** [comment]
The card is added to the customer, so if you want to query the cards, you'll need to retrieve the customer(s) using `ListCustomers` or `RetrieveCustomer` endpoint, which will have a `cards` field if applicable. This will have the `id` that you need to pass to the `CreatePayment` as the `source`.

**Comment by jaydeepw** [comment]
Do you mean using this API end points?

https://developer.squareup.com/reference/square/customers-api/list-customers

I dont see customer object having any card field in there.

**Comment by StephenJosey** [comment]
Yes, in the `Customer` object there is a array field called [cards](https://developer.squareup.com/reference/square/objects/Customer#definition__property-cards). If it's empty or not present, then you haven't saved a card to that particular customer.

**Comment by henry2327** [comment]
> Sí, en el `Customer`objeto hay un campo de matriz llamado [tarjetas](https://developer.squareup.com/reference/square/objects/Customer#definition__property-cards) . Si está vacío o no está presente, entonces no ha guardado una tarjeta para ese cliente en particular.

Hola Stephen josey le escribo para decirle algo sobre el plugin de square.. tengo una aplicación esta completamente echa entonce quiero agregar el plugin de square quien me ayudaría a integrarlo a mi aplicación puedo pagarles a una persona para que aga ese trabajo

**Comment by StephenJosey** [comment]
Hi @henry2327, we (Square) does not do any custom external development work, so you'll unfortunately need to find someone else to help with the development work.

**Comment by henry2327** [comment]
Oh pero tiene una persona que sepa  hacerlo voy a pagarle por el trabajo

**Comment by StephenJosey** [comment]
Ah ok got it. Please reach out to our API support for more general assistance then:  https://squareup.com/help/us/en/contact?panel=BF53A9C8EF68

**Comment by taqi92** [comment]
Hi @exgonline , the documentation says it will work with the sandbox test cards, you can get some from here https://developer.squareup.com/docs/devtools/sandbox/payments . i have tried with these cards & it worked.
