### ISSUE TITLE
{"errorMessage":"Server Not Authorized. Please check your server permission."

### ISSUE THREAD

**Issue by MATTYGILO** [square/in-app-payments-flutter-plugin#98]
### Describe the issue
I got this error
{"errorMessage":"Server Not Authorized. Please check your server permission."}
when running the command
`      curl -X POST 'my url' \
        -H 'Content-Type: application/json' \
        -d '{ "nonce": "valid nonce" }'`
note that where it says my url and valid nonce they are filled with the correct information

**Comment by StephenJosey** [comment]
Are you using the sample heroku backend, or your own server? This sounds like an error coming from the server, rather than Square.

**Comment by MATTYGILO** [comment]
> Are you using the sample heroku backend, or your own server? This sounds like an error coming from the server, rather than Square.
The guide makes it seem like you have to do both I'd prefer to use heroku

**Comment by StephenJosey** [comment]
You definitely do not need to do both, Heroku would be your server (you only need one backend server). I'm not sure I'm following, though - where did the error come from, then?

If you want to just use Heroku, follow step 4 of the quickstart: https://developer.squareup.com/docs/in-app-payments-sdk/quick-start/step-4
