### ISSUE TITLE
How to change "ZIP code" to "Postcode" in the card entry page?

### ISSUE THREAD

**Issue by wliumelb** [square/in-app-payments-flutter-plugin#99]
Hi, I am developing an e-commerce app for an Australian company. I really like the design of Square's card entry page, but I found a small issue with "ZIP code". 

My understanding is that "ZIP" is a term used exclusively in the United States, and people from other English speaking countries generally use 'postcode' or 'postal code' for the same thing. Is there any way to change the name of the field to make it look a bit less foreign to my Australian users? :)

**Comment by StephenJosey** [comment]
On Android, it automatically changes the field name based on the language of the device. On iOS, you need to add a language in XCode, by going to Project Info tab -> Localizations -> "+" button. Let me know if that doesn't work.

**Comment by wliumelb** [comment]
Thanks, Stephen. It works :)
